Patch 1
apple/swift-org-website pull request #230
Opened 2023-02-01 18:31 UTC by Zliced13

### Motivation:

I wanted to add scoop installation methods for swift, since I am the one who added it to [scoop](scoop.sh).

### Modifications:

I added scoop installation methods to these files, **getting-started/_installing.md** and the **download/_windows.md**

### Result:

**getting-started/_installing.md** and **download/_windows.md** will now have sections that detail how to install the dependencies and the Swift programming language using scoop.

2023-02-01 18:33 UTC, Zliced13 commented
This PR relates to #157.

2023-02-01 18:33 UTC, Zliced13 commented
@kaishin It's ready now.

2023-02-01 19:40 UTC, tomerd commented
@compnerd to approve

2023-02-28 20:57 UTC, compnerd requested changes

2023-02-28 20:57 UTC, compnerd commented on getting-started/_installing.md
> +   * Using the Windows Package Manager:
I think that this should be "Using Scoop"?

```suggestion
   * Using Scoop:
```

2023-02-28 20:57 UTC, compnerd commented on getting-started/_installing.md
>     The platform dependencies cannot be installed through the Windows Package Manager as the install rules do not install the components necessary.  They will be installed through Visual Studio instal
This seems a bit confusing now with two options.

```suggestion
   The platform dependencies cannot be installed through the currently supported package managers as the install rules do not install the components necessary.  They will be installed through Visual Studio installer.
```

2023-02-28 20:57 UTC, compnerd commented on getting-started/_installing.md
> +~~~
This is confusing here.  These are the instructions for installing using the Windows Package Manager.  Perhaps we should clarify that you can install these tools using documentation pointers?

2023-02-28 21:03 UTC, Zliced13 commented on getting-started/_installing.md
> +   * Using the Windows Package Manager:
Yes, my bad.

2023-02-28 21:05 UTC, Zliced13 commented on getting-started/_installing.md
> +~~~
Yes, I should have clarified that in the document. I'll fix it as soon as I can.

2023-03-01 04:10 UTC, Zliced13 commented on getting-started/_installing.md
> +~~~
It looks fixed already, looks good here.

2023-03-15 22:11 UTC, MaxDesiatov commented
@swift-ci test

2023-03-16 09:52 UTC, kaishin commented
@swift-ci test

2023-03-20 12:41 UTC, merged