WIP: Swift 5.8 release blog post
apple/swift-org-website pull request #257
Opened 2023-03-17 11:48 UTC by alexandersandberg

This is the first draft of the 5.8 release blog post. The PR is not yet marked as ready for review as we're waiting for more content to be added, but feel free to discuss changes and improvements already.

Thank you to everyone who contributed with content!

2023-03-17 11:57 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift-DocC also now supports documenting extensions to types from other modules. This is an opt-in feature, and can be [enabled by adding the `--include-extended-types` flag when using the Swift-DocC
Note: This link currently leads to a 404 as the content is pending deployment.

2023-03-17 11:57 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +- (?) SE-0380: [if and switch expressions](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md)
SE-0380 is marked as implemented in Swift 5.9, but it seems to have been cherry-picked into 5.8 in [this PR](https://github.com/apple/swift/pull/63378). Maybe @hborla can clarify?

2023-03-17 11:57 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +- (?) SE-0381: [DiscardingTaskGroups](https://github.com/apple/swift-evolution/blob/main/proposals/0381-task-group-discard-results.md)
SE-0381 seems to have been [cherry-picked into Swift 5.8](https://github.com/apple/swift/pull/62963), but it's still marked as "Accepted". @hborla do we need to update the evolution status?

2023-03-21 22:00 UTC, ktoso commented on _posts/2023-03-17-swift-5.8-released.md
> +- (?) SE-0381: [DiscardingTaskGroups](https://github.com/apple/swift-evolution/blob/main/proposals/0381-task-group-discard-results.md)
Discarding groups are accepted but didn’t make it into the SDKs… they ARE available on Linux toolchains though. We should explain this here a bit.

2023-03-22 16:29 UTC, hborla commented on _posts/2023-03-17-swift-5.8-released.md
> +- (?) SE-0380: [if and switch expressions](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md)
SE-0380 was reverted from the `release/5.8` branch in https://github.com/apple/swift/pull/63649. It's only implemented in Swift 5.9

2023-03-23 10:14 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +- (?) SE-0381: [DiscardingTaskGroups](https://github.com/apple/swift-evolution/blob/main/proposals/0381-task-group-discard-results.md)
I simply removed SE-0381 from the list for now, but feel free to suggest a way to list it without confusing people about the availability. 🙂

2023-03-23 19:11 UTC, dempseyatgithub commented on _posts/2023-03-17-swift-5.8-released.md
> +With the Swift 5.8-aligned release of [SwiftSyntax](https://github.com/apple/swift-syntax), SwiftSyntax contains a completely re-written parser that is implemented entirely in Swift instead of relyin
"the eventual goal is to eventually replace the old parser entirely"

too many 'eventually'. Maybe just "the eventual goal is to replace the old parser entirely."

2023-03-27 08:27 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +With the Swift 5.8-aligned release of [SwiftSyntax](https://github.com/apple/swift-syntax), SwiftSyntax contains a completely re-written parser that is implemented entirely in Swift instead of relyin
Great suggestion! Has been changed in 4992820.

2023-03-27 08:29 UTC, alexandersandberg commented
Rebased the PR with upstream/main.

2023-03-28 14:14 UTC, compnerd commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 continues the incremental improvements to the Windows toolchain. The following tries to highlight some of the important work that has gone into this release cycle.
```suggestion
Swift 5.8 continues the incremental improvements to the Windows toolchain. Some of the important work that has gone in this release cycles includes:
```

2023-03-28 14:21 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 continues the incremental improvements to the Windows toolchain. The following tries to highlight some of the important work that has gone into this release cycle.
I believe the correct grammar would be the following (based on Grammarly's suggestions):

- in -> into
- cycles -> cycle

```suggestion
Swift 5.8 continues the incremental improvements to the Windows toolchain. Some of the important work that has gone into this release cycle includes:
```

2023-03-28 17:03 UTC, tomerd commented on _posts/2023-03-17-swift-5.8-released.md
> +Here are some of the changes that have been introduced to [Swift Package Manager](https://github.com/apple/swift-package-manager) in Swift 5.8:
```suggestion
Following are some highlight from the changes introduced to the [Swift Package Manager](https://github.com/apple/swift-package-manager) in Swift 5.8:
```

2023-03-28 17:31 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Here are some of the changes that have been introduced to [Swift Package Manager](https://github.com/apple/swift-package-manager) in Swift 5.8:
👍 I think `highlight` -> `highlights` though?

2023-03-28 17:32 UTC, tomerd commented on _posts/2023-03-17-swift-5.8-released.md
> +Here are some of the changes that have been introduced to [Swift Package Manager](https://github.com/apple/swift-package-manager) in Swift 5.8:
updated

2023-03-28 17:52 UTC, dempseyatgithub requested changes

2023-03-28 18:04 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 is now officially released! 🎉 This release includes major additions to the [language and standard library](#language-and-standard-library) including piecemeal adoption of upcoming features,
I'm not sure if we want to add these anchor links to the below sections here or not. What do we think?

2023-03-28 18:41 UTC, amartini51 commented on _posts/2023-03-17-swift-5.8-released.md
> +[The Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/) book has been updated for Swift 5.8 and is now published with DocC. This is the offic
Is it also worth noting that TSPL is open for contributions?  We already highlighted that in a [blog post](https://www.swift.org/blog/tspl-on-docc/) for the first beta version that was built using DocC.

2023-03-28 18:45 UTC, amartini51 commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
```suggestion
Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. By default, upcoming features are disabled. To enable a feature, pass the compiler flag `-enable-upcoming-feature` followed by feature's identifier.
```

Avoiding passive voice and making it clearer that these are off unless you ask for them.

2023-03-28 19:20 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
Great suggestion! I feel like a "the" is missing though: "...followed by _the_ feature's..."

2023-03-28 19:23 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +[The Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/) book has been updated for Swift 5.8 and is now published with DocC. This is the offic
I think this would be great, but maybe in the Swift-DocC section instead where this is already talked about in more detail?

2023-03-28 20:14 UTC, stephentyrone commented on _posts/2023-03-17-swift-5.8-released.md
> +- SE-0374: [Add sleep(for:) to Clock](https://github.com/apple/swift-evolution/blob/main/proposals/0374-clock-sleep-for.md)
```suggestion
```

SE-0374 is not present in Apple's 5.8 release and we should simply omit it here to avoid potential confusion.

2023-03-29 01:56 UTC, dempseyatgithub commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
Is it important that readers know that an upcoming feature is a source-breaking language change coming in Swift 6 that they can adopt immediately?

2023-03-29 06:10 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +- SE-0374: [Add sleep(for:) to Clock](https://github.com/apple/swift-evolution/blob/main/proposals/0374-clock-sleep-for.md)
Would it be possible to learn about this by looking at the [Swift 5.8 evolutions list](https://www.swift.org/swift-evolution/#?version=5.8)?

SE-0374 is listed there for Swift 5.8, and we're referencing the list in the blog post, so the availability of this feature might be confusing.

2023-03-29 06:12 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
Maybe it's enough to link out to [the proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md) for those who want to learn more?

2023-03-29 10:52 UTC, buttaface commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 is now officially released! 🎉 This release includes major additions to the [language and standard library](#language-and-standard-library) including piecemeal adoption of upcoming features,
Maybe useful in the future, worth keeping IMO.

2023-03-29 11:59 UTC, buttaface commented on _posts/2023-03-17-swift-5.8-released.md
> +For more details please refer to [Swift Forums Post](https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192) that outlines the improvements and provides more information
`Swift Forums Post` -> the Swift Forums Post

2023-03-29 13:00 UTC, dempseyatgithub commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
Yes, you are probably right. It is probably impossible to capture all its subtleties in a short blurb.

2023-03-29 15:46 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +For more details please refer to [Swift Forums Post](https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192) that outlines the improvements and provides more information
Would lowercase "post."

2023-03-29 15:46 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 is now officially released! 🎉 This release includes major additions to the [language and standard library](#language-and-standard-library) including piecemeal adoption of upcoming features,
```suggestion
Swift 5.8 is now officially released! 🎉 This release includes major additions to the [language and standard library](#language-and-standard-library), including `hasFeature` to support piecemeal adoption of upcoming features, an improved [developer experience](#developer-experience), improvements to tools in the Swift ecosystem including [Swift-DocC](#swift-docc), [Swift Package Manager](#swift-package-manager), and [SwiftSyntax](#swiftsyntax), refined [Windows support](#windows-platform), and more.
```

A naive reading of the text as-is suggests that it's the Swift 5.8 release that adopts upcoming features piecemeal (a puzzling state of affairs, although I guess with the `clock(for:)` issue that's also technically true), rather than that it ships with a feature to allow _users_ to adopt upcoming features piecemeal. This wouldn't be confusing for those who've followed Swift Evolution closely, but I'd like to think our audience for this post would be broader than that.

2023-03-29 15:46 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +- SE-0354: [Regex literals](https://github.com/apple/swift-evolution/blob/main/proposals/0354-regex-literals.md) (`BaseSlashRegexLiterals`)
We expect that Objective-C forward declarations will have an "upcoming feature" designation shortly in time for Swift 5.8.

2023-03-29 15:46 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 brings other language and standard library enhancements, including unboxing for `any` arguments to optional parameters, enabling local wrapped properties in result builders, a new `@backDep
Maybe links for each of these so that the interested user can learn more? It occurs to me that existential unboxing could merit its own blog post too: it's a complex topic and it'd be nice to have didactic material about it.

Also, in terms of what examples we list here, the `@backDeployed(before:)` attribute is really cool but (by design) something that end users should be able to ignore, so I'd argue it's not necessarily a great choice to list here—I think a user who hasn't heard about it is as likely to find it puzzling as useful ("why do I need to know about this new feature? when would I need to use it?"—you don't, basically never).

```suggestion
Swift 5.8 brings other language and standard library enhancements, including unboxing for `any` arguments to optional parameters, local wrapped properties in result builders, the `@backDeployed(before:)` attribute to back-deploy functions on older OS versions, improved debug printing for key paths, and more.
```

2023-03-29 15:46 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +As [announced in February](https://www.swift.org/blog/tspl-on-docc/), The Swift Programming Language book has been converted to Swift-DocC and [open sourced](https://github.com/apple/swift-book), and
```suggestion
As [announced in February](https://www.swift.org/blog/tspl-on-docc/), The Swift Programming Language book has been converted to Swift-DocC and [open sourced](https://github.com/apple/swift-book), and with it came some enhancements to Swift-DocC itself in the form of [option directives](https://www.swift.org/documentation/docc/options) you can use to change the behaviour of your generated documentation. Swift-DocC has also added some new directives to create more [dynamic documentation pages](https://www.swift.org/documentation/docc/api-reference-syntax#creating-custom-page-layouts), including [grid-based layouts](https://www.swift.org/documentation/docc/row) and [tab navigators](https://www.swift.org/documentation/docc/tab).
```

Much as I'm a fan of King's English, being Canadian myself, my understanding is that standard documentation and communication is conducted in U.S. English, yes? In which case, "behaviour," "colour," "customise," "customisation" would need to be re-spelled.

2023-03-29 17:29 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +Swift 5.8 enables you to start incrementally preparing your projects for Swift 6 using _upcoming features_. Upcoming features are used with a new compiler flag `-enable-upcoming-feature FeatureIdenti
I added a link in https://github.com/apple/swift-org-website/pull/257/commits/bf4e3ed3c2b97d060de1ab0d0dcacc72e0952f3c.

2023-03-29 17:29 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +For more details please refer to [Swift Forums Post](https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192) that outlines the improvements and provides more information
Thanks! I have added both suggestions in https://github.com/apple/swift-org-website/pull/257/commits/427657ddef3a52cc3f4340f9110542c7438035c0.

2023-03-29 17:30 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +- The Windows toolchain has reduced some of the dependency on the environment variables. `DEVELOPER_DIR` was previously needed to locate components and this is no longer required. This cleans up the
👍 Updated in https://github.com/apple/swift-org-website/pull/257/commits/b141bb076efdd4bfff96e4dca2103e16aca688f6.

2023-03-29 17:38 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
From my understanding of the [examples in the proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md#feature-detection-in-source-code), `#/.../#` requires Swift 5.7 or above, which means it's not available in the `#else` here.

2023-03-29 17:53 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +As [announced in February](https://www.swift.org/blog/tspl-on-docc/), The Swift Programming Language book has been converted to Swift-DocC and [open sourced](https://github.com/apple/swift-book), and
While the blog is a bit more relaxed when it comes to styling (as we want to encourage authors to write in their own voice), I think a compilation of content like this—unless each section of content has a distinct author—should be consistent in styling across all contributions.

Therefore, I will change these as you've suggested. Thank you!

2023-03-29 18:56 UTC, amartini51 commented on _posts/2023-03-17-swift-5.8-released.md
> +[The Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/) book has been updated for Swift 5.8 and is now published with DocC. This is the offic
To me, it doesn't quite seem like the right organization for the DocC section to discuss contributing to TSPL.  TSPL is a project that uses DocC, but it's not part of DocC.

We could link to the README or the CONTRIBUTING file in the book's repo.

https://github.com/apple/swift-book/blob/main/CONTRIBUTING.md

2023-03-29 20:15 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +[The Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/) book has been updated for Swift 5.8 and is now published with DocC. This is the offic
I do agree, but as the open-sourcing of TSPL is [talked about in the DocC section](https://github.com/apple/swift-org-website/pull/257/files#diff-53d76ecf3c343ac9892cbd55408c09237cca4bc4e86b7f16f4f92df9b763d876R81), I think it might still be a suitable place.

2023-03-30 17:53 UTC, xwu commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
Good point; it should still be available if using Swift 5.8 (as is the implication here) but users who want code to compile in earlier versions wouldn't have that option. This brings me to another point: to use `hasFeature`, one would have to gate on `compiler(>=5.8)`, no? So perhaps this example ought to be:

```swift
#if compiler(>=5.8) && hasFeature(BareSlashRegexLiterals)
let regex = /.../
#elseif compiler(>= 5.7)
let regex = #/.../#
#else
let regex = try NSRegularExpression(pattern: "...")
#endif
```

2023-03-30 20:24 UTC, tkremenek commented
@swift-ci test

2023-03-30 20:49 UTC, airspeedswift commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
I don't think we should have the `#else`. For a start, the code won't really work as it implies because `NSRegularExpression` is not a swift regular expression.

I suggest just 

```
#if compiler(>=5.8) && hasFeature(BareSlashRegexLiterals)
let regex = /.../
#else
let regex = #/.../#
#endif
```

with code that assumes minimum tooling of 5.7.

2023-03-30 20:50 UTC, airspeedswift commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
(this is the norm fwiw, most code is written to work with the current and current-1 tools)

2023-03-30 21:10 UTC, airspeedswift commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
I removed the example – it's actually not even valid because the short-circuiting `&&` was only introduced in 5.8 so earlier tools can't handle it.

2023-03-30 21:32 UTC, alexandersandberg commented on _posts/2023-03-17-swift-5.8-released.md
> +let regex = try NSRegularExpression(pattern: "...")
👍 Probably best, to not raise any confusion. There are examples in the proposal for those interested.

2023-03-30 21:42 UTC, cthielen approved these changes

2023-03-30 21:51 UTC, 0xTim approved these changes
👏 @alexandersandberg

2023-03-30 21:52 UTC, 0xTim commented
@swift-ci test

2023-03-30 22:02 UTC, alexandersandberg commented
> 👏 @alexandersandberg

👏 to everyone who contributed with content and provided feedback! 🙂

2023-03-30 23:11 UTC, tomerd commented
🎊 🥳

2023-03-30 23:42 UTC, merged