Add blog post ‘Using Upcoming Feature Flags'
apple/swift-org-website pull request #308
Opened 2023-05-20 01:10 UTC by dempseyatgithub

This PR is for a technical blog post about upcoming feature flags, describing the problem they solve, the benefits using them to enable future features, and how to get started using them.

2023-05-20 01:10 UTC, dempseyatgithub commented
@swift-ci test

2023-05-20 02:49 UTC, dempseyatgithub commented
@swift-ci test

2023-05-20 16:43 UTC, tomerd commented
cc @cthielen

2023-05-22 06:38 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +```
The code syntax will be highlighted if we add a language to the code block. I think we should do this for all code blocks in the post, as I only see it being used for some atm.

```suggestion
```swift
```

|Before|After|
|---|---|
|<img width="438" alt="CleanShot 2023-05-22 at 08 36 29" src="https://github.com/apple/swift-org-website/assets/35671299/bbe06411-a542-42cb-9966-351eb74cd9eb">|<img width="433" alt="CleanShot 2023-05-22 at 08 36 10" src="https://github.com/apple/swift-org-website/assets/35671299/08f677ae-f07f-44e1-9dc3-c477434981ff">|

2023-05-22 06:42 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +To help meet this strong goal, the Swift project maintains an extensive [source compatibility test suite](https://www.swift.org/source-compatibility/){:target="_blank"}. Proposed changes are tested t
We should use relative swift.org links to not break future preview environments.

```suggestion
To help meet this strong goal, the Swift project maintains an extensive [source compatibility test suite](/source-compatibility/){:target="_blank"}. Proposed changes are tested to ensure they do not introduce source-breaking changes. In addition, each evolution proposal includes a discussion of source compatibility.
```

2023-05-22 06:44 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Use the [Swift Evolution Dashboard](https://www.swift.org/swift-evolution/){:target="_blank"} to find upcoming feature flags:
Another case where a relative link should be used.

```suggestion
Use the [Swift Evolution Dashboard](/swift-evolution/){:target="_blank"} to find upcoming feature flags:
```

2023-05-22 06:47 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each new release of Swift adds features and capabilities. These changes go through the [Swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md){:target="_blank"} where
I don't think we want to force new links to be opened in a new tab. This is not the usual, expected behavior, and I believe degrades the accessibility of the site. It should only be used in certain cases where it makes sense.

```suggestion
Each new release of Swift adds features and capabilities. These changes go through the [Swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md) where they are proposed, discussed by the community, and accepted.
```

Same suggestion applies to more links below.

2023-05-22 11:37 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +```
Thanks for catching this, I’ve added the `swift` language indicator to code blocks in the post.

2023-05-22 11:38 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +To help meet this strong goal, the Swift project maintains an extensive [source compatibility test suite](https://www.swift.org/source-compatibility/){:target="_blank"}. Proposed changes are tested t
Updated to use relative links where appropriate.

2023-05-22 11:39 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Use the [Swift Evolution Dashboard](https://www.swift.org/swift-evolution/){:target="_blank"} to find upcoming feature flags:
Resolved in latest commit

2023-05-22 11:42 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each new release of Swift adds features and capabilities. These changes go through the [Swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md){:target="_blank"} where
I’ve removed target=“_blank” from links in the post.

2023-05-22 11:42 UTC, dempseyatgithub commented
@swift-ci test

2023-05-22 12:09 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +</code></pre></div></div>
Why are we not using the markdown code block (```) here?

2023-05-22 12:30 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +</code></pre></div></div>
Because _UpcomingFeatureFlag_ is a placeholder and so it is emphasized / italicized to make the distinction, so it is clear that it is a placeholder. However, Markdown code blocks do not support emphasized text within the block, so it uses the equivalent HTML instead.

2023-05-22 12:41 UTC, alexandersandberg commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +</code></pre></div></div>
I see. I wonder if we can make the distinction in another way instead as hard-coded HTML is difficult to maintain.

I think TSPL is using this format:

```swift
-enable-upcoming-feature <#UpcomingFeatureFlag#>
```

(see e.g. [this](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types#Function-Type) or [this](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions#Ternary-Conditional-Operator) example)

2023-05-22 13:34 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +</code></pre></div></div>
I’m personally not a fan of that style. I think it can be confusing, leading the reader to think the `<#` and `#>` are required, but since there’s a concrete example immediately following, that should mitigate any confusion.

But yes, I agree with you that consistency with TSPL style and avoiding using hard-coded HTML outweigh my personal preference. I just pushed the change.

Also, since these two are not Swift code, removing the ‘swift’ language identifier. (With it in place, the `#`s are emphasized and looks particularly bad). Also had tried the ‘shell’ language identifier, but it considers everything after the first `#` to be a comment, so the remainder of the line is greyed out, making the angle brackets different colors.

So, leaving these two without a language identifier and rendering without syntax coloring.

2023-05-22 13:39 UTC, alexandersandberg approved these changes

2023-05-22 13:40 UTC, dempseyatgithub commented
@swift-ci test

2023-05-22 13:42 UTC, dempseyatgithub commented
@swift-ci test

2023-05-24 05:32 UTC, cthielen requested changes
James, this is a very well-written post! I left some minor comments to improve clarity and flow.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each new release of Swift adds features and capabilities. These changes go through the [Swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md) where they are proposed
Let's capitalize "Swift Evolution" since this is the first reference to the formal process.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The desired literal syntax is to enclose the regex pattern in forward slashes, as is the convention for regular expressions in many different tools and languages:
"as is the convention" => "which is the convention"

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The source breaking change does not come into effect until the next major language version—in this case Swift 6.
"in this case" is redundant

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Instead of a different compiler flag for each upcoming feature, the compiler gains one new flag that is followed by the name of the feature to be enabled:
"Instead of having" ? "Instead of creating"? "Instead of specify"? Feels like there's a word missing.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +For example, to enable the upcoming Regex literal syntax discussed above, you would use:
You can drop "discussed above"

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +You enable an upcoming feature on target by target basis by setting the compiler flag for a particular target.
"target-by-target"

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +You enable an upcoming feature on target by target basis by setting the compiler flag for a particular target.
"You enable an upcoming feature on target by target basis by setting the compiler flag for a particular target." could be simplified. How about "You enable an upcoming feature by setting the compiler flag for a given target."

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +For a Swift Package, enable upcoming features for a target in its `SwiftSetting` array in the package manifest:
"Swift package"

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +In Swift Package Manager manifests you specify these using a new `SwiftSetting`:
This section on SPM feels redundant with the later "In SPM Packages" section.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each dashboard entry links to full Swift evolution proposal where the upcoming feature flag is defined. Details on the changes that the flag enables are in the body of the proposal, typically in the
"Swift Evolution proposal" feels more appropriate here

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +## Valid Swift 5.8 Upcoming Feature Flags
What does "Valid" mean here? Should this simply be "Upcoming Swift 5.8 Feature Flags" or "Proposed Swift 5.8 Feature Flags"?

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +2. If your code compiles cleanly with the upcoming features enabled, then you know these features will not be an issue for you when you migrate to Swift 6.
This statement is fairly redundant with the logic presented in Step One. Also, this article generally talks about feature flags, but this bullet point makes them sound Swift 6-specific.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +## Benefits Of Enabling Upcoming Features
This section feels unnecessary. Or, if needed, a pithy version should go further up in the article - i.e. benefits is a good messaging point to start on, not end on.

2023-05-24 05:32 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Enabling upcoming features gives you a flexible way to migrate your code to adopt changes coming in Swift 6 at your own pace, feature by feature, target by target.
Do we need to be Swift 6-specific here?

2023-05-24 07:24 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each new release of Swift adds features and capabilities. These changes go through the [Swift evolution process](https://github.com/apple/swift-evolution/blob/main/process.md) where they are proposed
Changed in the latest commit.

2023-05-24 07:24 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The desired literal syntax is to enclose the regex pattern in forward slashes, as is the convention for regular expressions in many different tools and languages:
Changed in the latest commit.

2023-05-24 07:24 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The source breaking change does not come into effect until the next major language version—in this case Swift 6.
Removed in the latest commit.

2023-05-24 07:24 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Instead of a different compiler flag for each upcoming feature, the compiler gains one new flag that is followed by the name of the feature to be enabled:
Update to be “Instead of creating” in the latest commit.

2023-05-24 07:26 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +You enable an upcoming feature on target by target basis by setting the compiler flag for a particular target.
Changed in the latest commit.

2023-05-24 07:27 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +You enable an upcoming feature on target by target basis by setting the compiler flag for a particular target.
Updated to the suggested wording.

2023-05-24 07:27 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +For a Swift Package, enable upcoming features for a target in its `SwiftSetting` array in the package manifest:
Changed in latest commit.

2023-05-24 07:37 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +In Swift Package Manager manifests you specify these using a new `SwiftSetting`:
Yes, the intent of the ‘A Generalized Solution’ section is to describe all the pieces added by SE-0362 in a fairly pithy manner, so the reader gets an overview without delving into the step-by-step ‘how to use’ details.

Then later the ‘How To Enable Upcoming Features’ shows its usage in a more complete code sample.

For me, the adding of two lines to ‘A Generalized Solution’ to describe the feature completely outweighed seeing `.enableUpcomingFeature()` twice in the post.

I have also moved the ‘Benefits’ section up earlier, between these two sections, so I think that will make it read as less redundant.

2023-05-24 07:38 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Each dashboard entry links to full Swift evolution proposal where the upcoming feature flag is defined. Details on the changes that the flag enables are in the body of the proposal, typically in the
Changed

2023-05-24 07:42 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +## Valid Swift 5.8 Upcoming Feature Flags
Thanks for suggesting the heading be clarified.

I updated the section heading to "Upcoming Feature Flags Added In Swift 5.8”.

It literally describes what is listed, all of the upcoming feature flags that were added in Swift 5.8. It is a little wordy, but it is unambiguous and accurate.

2023-05-24 07:46 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +## Benefits Of Enabling Upcoming Features
I moved the “Benefits” section up to after the "A Generalized Solution” section.

So, right after the reader learns what upcoming feature flags are, the post tells them why they would want to use them. Then that is followed by how to use them, etc.

I agree having this come earlier in the post makes more sense as it motivates the rest of the post.

Note, I am still working on making the section pithier.

2023-05-24 07:47 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +Enabling upcoming features gives you a flexible way to migrate your code to adopt changes coming in Swift 6 at your own pace, feature by feature, target by target.
No, it’s not necessary. 

I changed ‘Swift 6’ to ‘next major release’.

2023-05-24 07:48 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +2. If your code compiles cleanly with the upcoming features enabled, then you know these features will not be an issue for you when you migrate to Swift 6.
Yes, it isn’t in the latest commit yet, but I will rework this section to be pithier.

2023-05-24 07:54 UTC, dempseyatgithub commented
> James, this is a very well-written post! I left some minor comments to improve clarity and flow.

Thank you! And thank you for your comments. They’ve been very helpful.

For comments that were straightforward changes, the changes are made and I resolved the conversations.

I left a few conversations unresolved with some comment by me, to get additional feedback from you. And I need to make the ‘benefits’ section more pithy - that is not checked in yet.

@cthielen

2023-05-24 18:44 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +### In SPM Packages
Thank you for noticing this. I think it’s often referred to as ‘SPM’ on external blogs, but we absolutely should use the correct name.

Changed in the latest commit.

2023-05-24 18:49 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +## Benefits Of Enabling Upcoming Features
I think some readers may not make the immediate connection between what the feature is and how it can benefit them, so I believe making the benefits clear is important.

I moved the ‘Benefits’ earlier in the article, right after the new feature is explained. I also reworked the section and it is shorter and I also think pithier and more clear and direct.

2023-05-25 00:27 UTC, dempseyatgithub commented
@swift-ci test

2023-05-25 01:26 UTC, dempseyatgithub commented
@swift-ci test

2023-05-26 05:07 UTC, cthielen approved these changes
Really good James! Can you set the publish date to Monday, May 29 at 10am? /cc @tkremenek

2023-05-26 05:07 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The source breaking change does not come into effect until the next major language version—Swift 6.
"language version—Swift 6" => "language version — Swift 6"

2023-05-26 05:07 UTC, cthielen commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> + -enable-upcoming-feature <#UpcomingFeatureFlag#>
I think you can simplify the fake flag by dropping the <#X#> and just go with "-enable-upcoming-feature SomeNewFeature"

2023-05-26 05:50 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> +The source breaking change does not come into effect until the next major language version—Swift 6.
Changed.

2023-05-26 05:52 UTC, dempseyatgithub commented on _posts/2023-05-19-using-upcoming-feature-flags.md
> + -enable-upcoming-feature <#UpcomingFeatureFlag#>
Changed. I called the placeholder ‘SomeUpcomingFeature’ but the same basic effect.

2023-05-26 05:54 UTC, dempseyatgithub commented
> Really good James! Can you set the publish date to Monday, May 29 at 10am? /cc @tkremenek

@cthielen  Yes, I incorporated your last pieces of feedback and have the file and post date updated to Monday, May 29 at 10am.

2023-05-26 05:54 UTC, dempseyatgithub commented
@swift-ci test

2023-05-26 17:45 UTC, tkremenek commented
Let's push the publish date to Tuesday.  Monday is a holiday in the USA.

2023-05-26 17:53 UTC, dempseyatgithub commented
The publish date is now updated for Tues, May 30.

@swift-ci test

2023-05-26 18:07 UTC, dempseyatgithub commented
@swift-ci test

2023-05-26 18:28 UTC, dempseyatgithub commented
@swift-ci test

2023-05-30 17:13 UTC, dempseyatgithub commented
@tkremenek @cthielen The publish date was updated for Tues, May 30.

2023-05-30 18:04 UTC, merged