Introduce top navigation
apple/swift-org-website pull request #450
Opened 2023-11-28 17:40 UTC by kaishin

### Motivation:

### Modifications:

### Result:

2023-12-10 23:59 UTC, compnerd commented
One thing that stands out to me is the ordering of the menubar items. Should we consider re-ordering things somewhat? Placing "Download" first because that is likely what people may want to do most. We can then order the other pieces in terms of importance (to the project and the visitor). As an example, perhaps:

- Download
- Getting Started
- Blog
- Community
- Packages
- Documentation

2023-12-17 11:27 UTC, alexandersandberg commented
>Placing "Download" first because that is likely what people may want to do most.

We want to guide visitors new to Swift to "Get started" as it's a better starting point for them, so I think it's best to keep "Download" last.

And I think recurring visitors who are experienced with Swift will easily find this "Download" item anyway.

2023-12-19 18:58 UTC, alexandersandberg commented on _includes/navigation.html
> +      <div id="menu-toggle" class="menu-item menu-toggle open"></div>
It would be great to turn this toggle into a `button` instead for better semantics/accessibility. We need to update the CSS to reset the browser styling as well though.

2023-12-19 19:02 UTC, kaishin commented on _includes/navigation.html
> +      <div id="menu-toggle" class="menu-item menu-toggle open"></div>
@alexandersandberg Good catch. I already did it for the in-menu toggles, so it's mostly applying the same class.

2023-12-19 19:37 UTC, alexandersandberg commented on _data/navigation.yml
> +      url: /packages/logging/
The package pages are broken currently, and need the `.html` suffix instead:

```suggestion
  pages:
    - title: Community Showcase
      url: /packages/showcase.html
    - title: Packages with Macros
      url: /packages/macros.html
    - title: Server
      url: /packages/server.html
    - title: Networking
      url: /packages/networking.html
    - title: Testing
      url: /packages/testing.html
    - title: Debug Logging
      url: /packages/logging.html
```

2023-12-22 15:33 UTC, kaishin commented
@tomerd I will keep cherry-picking commits from `apple:top-navigation` for now, instead of re-opening a new PR with that branch.

2023-12-27 19:25 UTC, kaishin reviewed
@swift-ci please test

2023-12-27 19:28 UTC, kaishin reviewed
This is now ready for review. The preview has been updated to reflect the most recent changes https://swift-org-website-kaishin.vercel.app.

2023-12-28 13:26 UTC, dempseyatgithub commented on _data/documentation.yaml
> +  - title: Language refrence (TSPL)
```suggestion
  - title: Language Reference (TSPL)
```

2023-12-28 13:48 UTC, dempseyatgithub commented on _data/documentation.yaml
> +#----------------------------------------------------
```suggestion
  - title: About Swift
    url: /about/
    description: |
      - A summary of the core features of Swift, supported platforms, and open source projects.
#----------------------------------------------------
```

It seemed that the About Swift page fit better as part of the Overview section as opposed to Articles. It also seemed strange to rename the page something like "Swift Overview" since the entire section is called Overview. So, I suggest leaving the name About Swift and having it at the end of the Overview section.

2023-12-28 14:06 UTC, dempseyatgithub commented on _data/documentation.yaml
> +      - The LLDB debugger provides a rich REPL as well as the debugging environment for the Swift Language.
```suggestion
      The LLDB debugger provides a rich REPL as well as the debugging environment for the Swift Language.
```
Remove the leading hyphen of the description field.

2023-12-28 15:02 UTC, dempseyatgithub commented on _includes/navigation.html
> +          <a href="/install">Download <strong>5.9.1</strong></a>
This should automatically pick up the latest version of Swift like the button on the main page does, so it does not need to be manually updated separately.

2023-12-28 15:26 UTC, dempseyatgithub commented
<img width="1135" alt="Screenshot 2023-12-28 at 9 56 55 AM" src="https://github.com/apple/swift-org-website/assets/470139/ad0947e8-0f2f-4c65-875c-6d627b4b0198">

A few pieces of feedback about the top navigation menu:

1. The menu items seem to visually center on the top bars of the 'ft' in the Swift logo. I think this makes the menu items appear too high in the menu bar.

2. The underline under the Download menu item makes it seem like that item is permanently selected. Is the underline necessary? I think being on the right margin already gives the Download item a good amount of weight.

3. I don't think the version number in the Download menu item needs to be bold. It draws a lot of attention to the version, when really the action "Download" is probably the more important of the two. I suggest removing the bold.

4. I think the letter spacing works well for the other menu items, but I don't think it works well for the version number in the Download link. Consider wrapping the version in a span with zero letter spacing:

Current:
<img width="147" alt="Screenshot 2023-12-28 at 10 19 29 AM" src="https://github.com/apple/swift-org-website/assets/470139/ae68eadd-139e-4059-b2aa-a4a7b326c35a">

Version with zero additional letter spacing:
<img width="153" alt="Screenshot 2023-12-28 at 10 17 32 AM" src="https://github.com/apple/swift-org-website/assets/470139/908470f1-c80d-4e4c-8ca2-d1d376a38583">

5. The drop down menu triangles seem very far away from their menu items. Could they be brought in closer to the menu item name?

2023-12-28 15:30 UTC, dempseyatgithub commented
@kaishin Would you be able to make a change in `about/index.md`? It seems the easiest way to add to your PR.

At the end of the file `about/index.md`, could you reverse the two includes so they are ordered like this?

```
{% include_relative _platform-support.md %}
{% include_relative _open-source.md %}
```

This was one of the changes we had talked about for this page.

2023-12-28 15:45 UTC, dempseyatgithub commented on _data/documentation.yaml
> +      The Swift Programming Language book is the authoritative reference for Swift,
```suggestion
      The Swift Programming Language (TSPL) book is the authoritative reference for Swift,
```
Usually an abbreviation is defined immediately following the first use of the full term. Moving the abbreviation here instead of in the title.

2024-01-17 01:38 UTC, shahmishal commented
Overall, this is a great improvement compared to the current nav. However, we should look into highlighting the current selected item or add a title to the blog posts page. https://swift-org-website-kaishin.vercel.app/blog/ 

<img width="1147" alt="Screenshot 2024-01-16 at 5 38 24 PM" src="https://github.com/apple/swift-org-website/assets/2727770/1c3e2ec0-bbe6-4ff0-8930-5cdf6aa9bf74">

2024-01-17 06:49 UTC, shahmishal commented
This work can be done in follow up pull request: https://github.com/apple/swift-org-website/issues/480

2024-01-17 11:42 UTC, 0xTim approved these changes
Ship it!

2024-01-17 12:18 UTC, alexandersandberg requested changes
As we've moved documentation pages to `/documentation` we need to add redirects.

For instance, https://swift.org/package-manager and https://swift.org/server will no longer work. It's important that we fix this before merging as the first link is one of the most visited on the website.

This is not an exhaustive list, just some links that I noticed. We probably need more redirects than those 2 above.

2024-01-18 23:44 UTC, tomerd commented
> As we've moved documentation pages to /documentation we need to add redirects.

> For instance, https://swift.org/package-manager and https://swift.org/server will no longer work. It's important that we fix this before merging as the first link is one of the most visited on the website.

> This is not an exhaustive list, just some links that I noticed. We probably need more redirects than those 2 above.

@alexandersandberg would you like to address this?

2024-01-18 23:51 UTC, tomerd commented
@alexandersandberg example for these two pages: https://github.com/apple/swift-org-website/pull/484

2024-01-20 06:28 UTC, tomerd commented
@kaishin with https://github.com/apple/swift-org-website/pull/484 merged we should be good to go

2024-01-20 15:32 UTC, tkremenek approved these changes

2024-01-20 15:33 UTC, tkremenek commented
> @kaishin with #484 merged we should be good to go

The PR says that changes are still requested.

2024-01-20 15:45 UTC, alexandersandberg commented
> > @kaishin with #484 merged we should be good to go
> 
> The PR says that changes are still requested.

We still need to merge those changes into this PR to fix the redirects.

2024-01-22 17:37 UTC, tomerd commented
@kaishin think this is ready to merge, but we just need to rebase. would you like to do so, or prefer I rebased and merged?

2024-01-22 17:38 UTC, tomerd approved these changes

2024-01-22 17:50 UTC, shahmishal approved these changes
LGTM! Thank you!

2024-01-23 06:07 UTC, tomerd commented
@swift-ci test

2024-01-23 06:43 UTC, alexandersandberg approved these changes
🚢

2024-01-23 06:47 UTC, alexandersandberg commented
@swift-ci please test

2024-01-23 14:24 UTC, kaishin commented
@swift-ci please test

2024-01-23 14:45 UTC, merged