Benchmark blog post
apple/swift-org-website pull request #460
Opened 2023-12-11 18:51 UTC by hassila

Benchmark blog post draft as previously agreed, I put in December 15 as publication date as a placeholder, looking forward to your feedback.

2023-12-14 09:29 UTC, ktoso approved these changes
LGTM, this is a great post (and project)!

Thank you for the post, I think it’s great — just a few minor “yay!” and rephrasing ideas inline.

2023-12-14 09:29 UTC, ktoso commented on _posts/2023-12-15-benchmarks.md
> +Have you ever encountered a _performance problem_ that slipped through to end users? Do you systematically measure and validate performance metrics when making changes to your Swift package?
Love the opening line :-)

2023-12-14 09:29 UTC, ktoso commented on _posts/2023-12-15-benchmarks.md
> +It is suitable both for microbenchmarks mostly concerned with CPU usage as well as for more complex long-running benchmarks focused on [multiple performance metrics](https://swiftpackageindex.com/ord
Great to callout HDRH, that rings all the right bells for people familiar with it :)

2023-12-14 09:29 UTC, ktoso commented on _posts/2023-12-15-benchmarks.md
> +Performance is a key non-functional feature for many foundational packages and applications, both server-side and in the desktop/mobile space.
Or non-functional requirement? Feels like a stronger word but either is fine ofc

2023-12-14 09:29 UTC, ktoso commented on _posts/2023-12-15-benchmarks.md
> +* Multiple output formats (console text format, markdown, JMH analytics, HDR histogram output, ...)
Thx for calling out the JMH format :) that’s cool because of existing visualization tools etc

2023-12-14 09:34 UTC, hassila commented on _posts/2023-12-15-benchmarks.md
> +Performance is a key non-functional feature for many foundational packages and applications, both server-side and in the desktop/mobile space.
Agree, changed in [d2e7903](https://github.com/apple/swift-org-website/pull/460/commits/d2e7903f30985296f4392fdc8957000a5ca9b51e)

2023-12-14 10:48 UTC, MahdiBM reviewed
Nice one :)

Just pointing out that the png should probably have a white/transparent background, but maintainers can let you know better if the black background is actually an issue or not 🙂

2023-12-14 10:48 UTC, MahdiBM commented on _posts/2023-12-15-benchmarks.md
> +* Custom performance metrics (for other contrained resources)
```suggestion
* Custom performance metrics (for other constrained resources)
```

2023-12-14 11:43 UTC, hassila commented
> Nice one :)
> 
> Just pointing out that the png should probably have a white/transparent background, but maintainers can let you know better if the black background is actually an issue or not 🙂

Thanks @MahdiBM! Fixed up the background, it definitely was an issue in light mode, I missed that.

2023-12-17 11:11 UTC, alexandersandberg reviewed
Very nice blog post!

I left some smaller comments. 🙂

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +Now, this is primarily focused on the _CPU_ performance metric - but the CPU is only one of several resources which are constrained, there are many more;
I'm no expert here, but I feel like this would read better.

```suggestion
Now, this is primarily focused on the _CPU_ performance metric, but the CPU is only one of several resources which are constrained — there are many more:
```

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +Constructing a set of benchmarks and consistently running them provides an indication when something is not performing as expected. Typically, other more specialized tools are employed for a root-cau
TIL most American style guides recommend "e.g." and "i.e." to be followed by a comma. More important is consistency though, so I would suggest either removing the comma here or adapting it for the rest of the blog post.

```suggestion
Constructing a set of benchmarks and consistently running them provides an indication when something is not performing as expected. Typically, other more specialized tools are employed for a root-cause analysis to analyze and fix the problem (e.g. Instruments, DTrace, Heaptrack, Leaks, Sample, …).
```

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +This is analogous with unit tests, where a failed test provides an indication that something is wrong, and other more specialized tools are used to fix the problem (e.g., a debugger, TSAN/ASAN, addin
See my other comment on this.

```suggestion
This is analogous with unit tests, where a failed test provides an indication that something is wrong, and other more specialized tools are used to fix the problem (e.g. a debugger, TSAN/ASAN, adding asserts, debug printouts, …)
```

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +The Benchmark package has recently seen a wide community uptake as more projects focuses on performance, including e.g.
```suggestion
The Benchmark package has recently seen a wide community uptake as more projects focus on performance, including e.g.
```

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +Discussions and questions is best directed to [the Swift forums section for Benchmark](https://forums.swift.org/c/related-projects/benchmark/105).
```suggestion
Discussions and questions are best directed to [the Swift forums section for Benchmark](https://forums.swift.org/c/related-projects/benchmark/105).
```

2023-12-17 11:11 UTC, alexandersandberg commented on _posts/2023-12-15-benchmarks.md
> +help you to ship software with consistent performance and controlled resource usage that delights your users.
```suggestion
Performance is a key non-functional feature for many software packages. Early and continuous benchmarking will help you to ship software with consistent performance and controlled resource usage that delights your users.
```

2023-12-17 11:11 UTC, alexandersandberg commented on assets/images/benchmark-blog/Benchmark.png
This file is quite large, so it would be great to try to compress it a bit. For instance, I managed to reduce it to ~200kb by dropping it into https://tinypng.com.

2023-12-17 13:59 UTC, hassila commented on _posts/2023-12-15-benchmarks.md
> +Constructing a set of benchmarks and consistently running them provides an indication when something is not performing as expected. Typically, other more specialized tools are employed for a root-cau
Applied comman consistently in [104bf15](https://github.com/apple/swift-org-website/pull/460/commits/104bf1589b3b0b17ca68be20a0aabcf02b81b662)

2023-12-17 14:05 UTC, hassila commented
> Very nice blog post!
> 
> I left some smaller comments. 🙂

Thanks Alexander, much appreciated! All points addressed by [88ff868](https://github.com/apple/swift-org-website/pull/460/commits/88ff868aadeec50a8b16a99fc758bd5f40dc602b).

2023-12-17 15:11 UTC, alexandersandberg approved these changes

2023-12-19 16:12 UTC, 0xTim approved these changes
One minor nit but overall looking forward to sharing this!

2023-12-19 16:12 UTC, 0xTim commented on _posts/2023-12-21-benchmarks.md
> +* CPU
We already mention this above, feels like we should rework the list or the introduction to the list

2023-12-19 16:33 UTC, hassila commented on _posts/2023-12-21-benchmarks.md
> +* CPU
Thanks @0xTim - I tried to address this in https://github.com/apple/swift-org-website/pull/460/commits/bec69e7c8fe18f431b21c24140a6ca7af6c344df - I think it turned out better, but let me know if you have any other suggestion,.

2023-12-19 18:24 UTC, alexandersandberg commented on _posts/2023-12-21-benchmarks.md
> +date: 2023-12-21 10:00:00
Just FYI, the editorial team usually updates this right before merging and publishing anyway, so it's ok to leave it in the past. 🙂

2023-12-19 18:43 UTC, hassila commented on _posts/2023-12-21-benchmarks.md
> +date: 2023-12-21 10:00:00
Ah, thanks!

2024-01-06 12:04 UTC, finagolfin commented on _posts/2023-12-21-benchmarks.md
> +Introductory getting started information is available both on the [package GitHub page](https://github.com/ordo-one/package-benchmark) as well as in the [Swift Package Index DocC documentation](https
Add a period at the end of the sentence, ie after the link.

2024-01-06 12:05 UTC, finagolfin commented on _posts/2023-12-21-benchmarks.md
> +Swift's ambitious aspirations is that the language should provide:
aspirations is -> aspirations are

2024-01-06 12:10 UTC, finagolfin commented on _posts/2023-12-21-benchmarks.md
> +* Automated Pull Request check vs. a pre-recorded *absolute baseline p90 threshold* (see e.g., [Swift Certificates](https://github.com/apple/swift-certificates/tree/main/Benchmarks) for such a workfl
". Suitable" -> ", suitable"

2024-01-06 12:13 UTC, finagolfin commented on _posts/2023-12-21-benchmarks.md
> +* Multiple output formats (console text format, markdown, JMH analytics, HDR histogram output, ...)
This last list seems redundant.

2024-01-06 12:18 UTC, finagolfin commented
Good post, but it would benefit from some motivation. Obviously this filled a need in your own work, maybe you could tell the story of how this package got started or some important incident where it caught some performance regression?

Such stories help motivate a post with real-world examples, would be great if you can add one or two.

2024-01-08 09:56 UTC, hassila commented
Thanks @finagolfin - addressed the straightforward fixes in [bd96a6e](https://github.com/apple/swift-org-website/pull/460/commits/bd96a6e2a48d7696d7cf4f94ea7554e31630a10d) - will think if there's any good additional motivation/background we can add which doesn't just focus on our niche (tried to motivate it with the analogy to unit testing which seems fairly straightforward as an argument for the need for non-functional requirement validation).

2024-01-08 10:20 UTC, finagolfin commented
Your niche is fine too, as that is a big market.

2024-01-09 09:54 UTC, hassila commented
> Your niche is fine too, as that is a big market.

Ok, did a stab at https://github.com/apple/swift-org-website/pull/460/commits/43290b5baf9f3f0fd2a4f96a76fbac8a031cff92 with some background.

2024-02-02 15:44 UTC, hassila commented
So I guess this is stuck at review with the blog post owners, or is there anything else to do?

2024-02-02 15:45 UTC, alexandersandberg commented
cc: @cthielen

2024-03-13 05:09 UTC, cthielen requested changes

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +In the realm of professional trading software, the role of a comprehensive benchmarking framework integrated with Continuous Integration (CI) parallels the importance of unit and integration testing.
This is a good spot to take your "Have you ever encountered a performance problem" point, i.e. it's apparent in trading systems why performance is important, but it's important to the average developer too, who doesn't want poor or regressed performance.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +After examining the existing infrastructure within the Swift ecosystem, we concluded that there were no existing solutions meeting our needs for multi-platform and rich metrics support, CI integratio
Minor nit but "open source", not "open-source"

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +Constructing a set of benchmarks and consistently running them provides an indication when something is not performing as expected. Typically, other more specialized tools are employed for root-cause
It's not clear what "other more specialized tools" is talking about. I believe the point is that software analysis requires specialized tools, e.g. memory leak detectors for memory leaks, etc., and benchmarking fits in here for performance regressions - it's another specialized tool. Better to state that plainly.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +
This would be a good place for a bulleted list of the types of metrics that `package-benchmark` can gather.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +There's an [introduction to writing benchmarks](https://swiftpackageindex.com/ordo-one/package-benchmark/documentation/benchmark/writingbenchmarks) as well as a [sample repository](https://github.com
Not sure I follow "a minimalistic and one more complex benchmark could look like"?

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +There's an [introduction to writing benchmarks](https://swiftpackageindex.com/ordo-one/package-benchmark/documentation/benchmark/writingbenchmarks) as well as a [sample repository](https://github.com
If it's in reference to the sample showing both a minimal benchmark and a slightly more complex one, it'd be better as two code samples instead of one.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +### Performance metrics
This is a good section but it feels like a condensed version of it belongs in your introduction, not after you start diving into the package.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +### Key Benchmark workflows are supported
For better or worse, Swift.org is All Caps All The Time, e.g. "Key Benchmark Workflows Are Supported"

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +* **[Automated Pull Request performance regression checks](https://swiftpackageindex.com/ordo-one/package-benchmark/documentation/benchmark/comparingbenchmarksci)** by comparing the performance metri
Why are these bolded?

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +### Community Adoption
Good info, but this doesn't need its own section. Recommend folding it into your conclusion.

2024-03-13 05:09 UTC, cthielen commented on _posts/2023-12-21-benchmarks.md
> +Performance is a key non-functional requirement for many software packages. Early and continuous benchmarking will help you to ship software with consistent performance and controlled resource usage
I'd recommend a shorter wrap-up here with a call-to-action, e.g. "Give it a try". You don't want to be listing virtues here.

2024-03-13 15:19 UTC, hassila commented
Thanks for the extensive feedback @cthielen, I have tried to address it in [4744b04](https://github.com/apple/swift-org-website/pull/460/commits/4744b047fdbc2138ff25946f5ad62da6f8f07303)

2024-03-14 04:43 UTC, hassila commented on _posts/2023-12-21-benchmarks.md
> +
I added the full list, but perhaps it'd read better to list the categories of metrics instead, wdyt?

2024-03-19 05:25 UTC, cthielen commented
@hassila Thank you! Are you okay if I publish this (i.e. I'll adjust the date and merge) on Wednesday, 1/20 around 10am Pacific?

2024-03-19 05:29 UTC, hassila commented
Thanks @cthielen that'd be perfectly fine, thanks.

2024-03-19 05:53 UTC, cthielen commented
@swift-ci please test

2024-03-20 17:01 UTC, cthielen approved these changes

2024-03-20 17:06 UTC, cthielen commented
@swift-ci please test

2024-03-20 17:06 UTC, shahmishal commented
@swift-ci please test

2024-03-20 17:09 UTC, merged