Update and refine the Heroku deployment guide
apple/swift-org-website pull request #472
Opened 2023-12-31 16:13 UTC by shagedorn

### Motivation:

Update to recent versions so newcomers can use examples from this guide directly without further changes. Additional context was added to make it easier to understand how Heroku works in general.

### Modifications:

- update to latest Heroku stack
- change default branch name to `main`
- fix outdated/broken links
- consistent formatting & capitalization
- additional links and high-level overview

### Result:

A hopefully easier-to-follow guide :)

2023-12-31 16:16 UTC, shagedorn commented on server/guides/deploying/heroku.md
> +For your Heroku application, you only need to select a virtual operating system ([stack](#stack-selection)) and preinstalled software packages ([buildpack](#buildback-selection)). After installing He
I feel a high-level overview helps to decide between the various deployment options, especially for people (like me) with little server-side experience 🙂

2023-12-31 16:16 UTC, shagedorn commented on server/guides/deploying/heroku.md
> +brew tap heroku/brew && brew install heroku
Copied directly from the [official guide](https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli).

2023-12-31 16:16 UTC, shagedorn commented on server/guides/deploying/heroku.md
> -As of 13 September 2018, Heroku’s default stack is Heroku 18, we need it to be 16 for swift projects.
I believe the last part is not needed anymore, `16` is in the end-of-life phase and unlikely to be useful for any new project.

2024-01-02 11:05 UTC, 0xTim requested changes
Thanks for this! A few small changes but overall pretty much there!

2024-01-02 11:05 UTC, 0xTim commented on server/guides/deploying/heroku.md
> +### Login
Nit - should be two words
```suggestion
### Log In
```

2024-01-02 11:05 UTC, 0xTim commented on server/guides/deploying/heroku.md
> +Now that we have added the `.swift-version` and `Procfile` files, make sure these are committed on `main` to be included in your deployment.
I think for a tutorial like this, adding a couple of lines showing the `git add` and `git commit` commands is a good idea

2024-01-02 11:05 UTC, 0xTim commented on server/guides/deploying/heroku.md
>  git push heroku master
This should now be `main` right?

2024-01-02 13:23 UTC, shagedorn commented on server/guides/deploying/heroku.md
> +### Login
Wouldn't it be a single word, when written/interpreted as a noun? I tried to make it consistent to use primarily nouns for the section titles 🙂

2024-01-02 13:23 UTC, shagedorn commented on server/guides/deploying/heroku.md
>  git push heroku master
Absolutely, thanks! Will fix shortly.

2024-01-02 18:11 UTC, shagedorn commented
I added a fixup commit for better change reviewability. Let me know if you want me to squash things together, or if you'll squash-merge via GitHub anyway (once you're happy with the changes).

2024-01-04 17:00 UTC, shagedorn commented
@0xTim should be ready for another look, if you have a moment 🙂 🙏🏻

2024-01-06 01:08 UTC, 0xTim commented on server/guides/deploying/heroku.md
> +### Login
AFAIK "Login" isn't a real word - I'm just relaying what my editor told me circled in virtual giant red ink when I wrote a book 😆 but it's not a hill I'm overly attached to

2024-01-06 01:08 UTC, 0xTim approved these changes

2024-01-06 01:08 UTC, 0xTim commented
@swift-ci please test

2024-01-06 01:11 UTC, merged