Make template wider
apple/swift-org-website pull request #499
Opened 2024-01-26 19:28 UTC by federicobucchi

### Motivation:

The new navigation opened the possibility to make the whole template wider.  This would reduced scrolling, content space and, for the homepage case, the main content displayed without having to scroll.  The other pages are also receiving the same benefits.

### Modifications:

Changed the CSS in:
```
assets/stylesheets/_screen.scss
assets/stylesheets/core/_vars.scss
assets/stylesheets/pages/_landing.scss
```

Changed the structure of the `callout` section in homepage in:
```
index.md
```

### Result:

<img width="1441" alt="Screenshot 2024-01-25 at 3 26 21 PM" src="https://github.com/apple/swift-org-website/assets/59409/908832aa-6ea6-4039-8552-3d1af9864fdd">

<img width="1445" alt="Screenshot 2024-01-25 at 3 26 30 PM" src="https://github.com/apple/swift-org-website/assets/59409/389b2daa-68fe-4fb7-bd50-df6e8478146f">

<img width="1438" alt="Screenshot 2024-01-25 at 3 26 56 PM" src="https://github.com/apple/swift-org-website/assets/59409/fbcb7f91-5a20-4983-b248-566762073e05">

<img width="564" alt="Screenshot 2024-01-25 at 3 49 08 PM" src="https://github.com/apple/swift-org-website/assets/59409/2785e297-dd12-44eb-999e-7561a1fe270a">

<img width="1056" alt="Screenshot 2024-01-25 at 3 49 37 PM" src="https://github.com/apple/swift-org-website/assets/59409/2e36f8b0-16f5-4d36-ac02-d4d297187afc">

<img width="804" alt="Screenshot 2024-01-25 at 3 49 45 PM" src="https://github.com/apple/swift-org-website/assets/59409/a51cec23-4bd2-42d4-bbf9-a9b72e83ff4f">

2024-01-27 09:33 UTC, kaishin commented
@federicobucchi Thank you for the PR. We will bring this up within the workgroup as changing the content width will affect the readability of text content in pages such as the blog. We are already above the [recommended ranges for line length](https://baymard.com/blog/line-length-readability).

2024-01-30 22:01 UTC, federicobucchi commented
@kaishin maybe we could have "blog, articles, docs" pages keeping the old template and pages with boxes, being able to spread:

<img width="1399" alt="Screenshot 2024-01-30 at 1 52 06 PM" src="https://github.com/apple/swift-org-website/assets/59409/e0e24b55-97c8-4974-8048-cfde6b856cde">

---

<img width="1401" alt="Screenshot 2024-01-30 at 1 52 19 PM" src="https://github.com/apple/swift-org-website/assets/59409/1526b28c-abb4-4770-9ff1-b32a1d5e9079">

2024-01-31 13:05 UTC, kaishin commented
@federicobucchi That's a good compromise indeed! Basically any page that's "single column" we use the current, otherwise the new full width layout, correct?

2024-01-31 16:53 UTC, federicobucchi commented
> @federicobucchi That's a good compromise indeed! Basically any page that's "single column" we use the current, otherwise the new full width layout, correct?

@kaishin correct!  I noticed that specifically the pages with a single column are in Blog, Documentation and some other Misc pages (I went through all pages and verified)

2024-01-31 17:56 UTC, shahmishal commented
Thank you for working on this! I was wondering is the plan to change the color of bold text on home page part of this PR expected? 
<img width="258" alt="Screenshot 2024-01-31 at 9 56 17 AM" src="https://github.com/apple/swift-org-website/assets/2727770/a1c466fb-f5a2-40dc-8de7-0b0815c4b929">

2024-01-31 20:00 UTC, federicobucchi commented
> Thank you for working on this! I was wondering is the plan to change the color of bold text on home page part of this PR expected?

@shahmishal I did it to highlight how the `callout` section would look having the opportunity to increase the text and move up the `code` box.  The text would become a little "boring" just like that, so highlighting the keywords would help.  The add  of color can be done in another PR if it is preferred (the color used was already included as variable in the codebase).  Otherwise if a new PR is not needed, I can also move it in its own commit.  Just let me know the preference!

2024-01-31 20:35 UTC, kaishin commented
> I noticed that specifically the pages with a single column are in Blog, Documentation and some other Misc pages (I went through all pages and verified)

That sounds good!

---

@federicobucchi I think review would go faster if we have one PR for each individual change. Some of these changes might require more discussion than others. For instance the layout change at the top section and the color might slow down the review of the content-width change :)

2024-02-01 18:24 UTC, shahmishal approved these changes
LGTM!

2024-02-01 19:36 UTC, alexandersandberg reviewed
I think the CSS for the new `.list` was accidentally reverted as well. I currently don't see any difference.

2024-02-01 19:42 UTC, federicobucchi commented
Thank @alexandersandberg : https://github.com/apple/swift-org-website/pull/499/commits/d0506c8e35a6519c53e56165ec09f41ba3865727

2024-02-01 20:04 UTC, alexandersandberg reviewed
I think this is a great change! I'm just confused with the different layout types now. I get that `post` and `list` are now for the more narrow layout, but shouldn't `page` also use the narrow layout?

For instance, I think /documentation/cxx-interop/status/ would read better as a `list` (narrow) as it's an article (actually, maybe it should have the `article` layout, and we apply the narrow style to there as well).

Looking at more of the remaining `page` layouts, I feel like most of them could use the narrow layout.

**What if we don't add `list` but just reuse `page` instead as the narrow layout?**

We could maybe even merge `article` into `page`, and conditionally apply the "Contributed by" byline based on the availability of the `author` data, although that can be done in a separate PR.

2024-02-01 23:53 UTC, federicobucchi commented on documentation/articles/value-and-reference-types.md
> +layout: list
I have brought `article` back and like you said we can do a change of conditional "Contributed by" in a following PR.

2024-02-01 23:53 UTC, federicobucchi commented
@alexandersandberg 

I have introduced a new `list` layout because we have some `page` layouts that need to be one column only (narrow) and some "2 columns" (wider), and in the `list` layout having an `<article />` because of mostly text (representing almost a `post` but being a `page`

For example:
https://www.swift.org/getting-started/
This page is currently layout `page`, and it makes sense to me to have it wider because the elements are placed in a "more than one column template".

https://www.swift.org/documentation/
Also this page is currently layout `page`, but since it is mostly text, it will need to stay narrow (what I called it `list`)

Same thing with https://www.swift.org/blog/

I decided to go with the `list` name because I couldn't find a better way to describe with one word the something that I would define a "page with all text that needs to have only one column".  I am of course open to other suggestions.

2024-02-02 08:12 UTC, alexandersandberg reviewed
Thanks for the additional explanation!

Then I would argue that the following pages, which also mostly are text, should be `list` (narrow) instead of `page` (wide):

<details>
<summary>33 pages</summary>

* CONTRIBUTORS.md
* community/index.md
* website-workgroup/index.md
* website-governance/index.md
* sswg-survey-2023/index.md
* sswg/incubation-process.md
* migration-guide-swift3/se-0107-migrate.md
* sswg/security/index.md
* sswg/security/contributor-found-vulnerability.md
* sswg/security/package-requirements.md
* sswg/security/package-maintainer-received-vulnerability-report.md
* documentation/cxx-interop/project-build-setup/index.md
* documentation/cxx-interop/status/index.md
* documentation/server/guides/allocations.md
* documentation/server/guides/building.md
* documentation/server/guides/deployment.md
* documentation/server/guides/index.md
* documentation/server/guides/linux-perf.md
* documentation/server/guides/llvm-sanitizers.md
* documentation/server/guides/memory-leaks-and-usage.md
* documentation/server/guides/packaging.md
* documentation/server/guides/performance.md
* documentation/server/guides/setup-and-ide-alternatives.md
* documentation/server/guides/testing.md
* documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
* documentation/server/guides/deploying/aws-sam-lambda.md
* documentation/server/guides/deploying/aws.md
* documentation/server/guides/deploying/digital-ocean.md
* documentation/server/guides/deploying/gcp.md
* documentation/server/guides/deploying/heroku.md
* documentation/server/guides/deploying/ubuntu.md
* documentation/server/guides/libraries/concurrency-adoption-guidelines.md
* documentation/server/guides/libraries/log-levels.md
</details>

This leaves us with 2 pages with the `page` layout:

* /getting-started/index.md
* /packages/index.md

I would instead propose that we keep the pages with the `page` layout as is and instead only change the layout for these few wider pages. What about a `page-wide` template?

We might have to add an `<article>` tag to the `page` layout if we still want the default (e.g. home page) to be wide.

Does that make sense? Then we can change the layout of 2 files instead of ~100 or so, and I think it makes more sense than having ~100 `list` pages and 2 `page` pages. 🙂

2024-02-02 17:17 UTC, federicobucchi commented on _layouts/article.html
> +layout: post
The problem with that is the `<h1>{{ page.title }}</h1>` outside the `{{content}}`
So I switched to `default` and added the title inside the `article`
And this will be easier with: https://github.com/apple/swift-org-website/pull/511

2024-02-02 17:17 UTC, federicobucchi commented
@alexandersandberg 

I applied your suggestion `page-wide`, but I had to apply `<article>` like you said around as container

2024-02-02 17:19 UTC, federicobucchi commented
@swift-ci please test

2024-02-02 17:23 UTC, federicobucchi commented
@swift-ci please test

2024-02-02 17:29 UTC, alexandersandberg commented on index.md
> -title: Welcome to Swift.org
This title is used in `<head>` for meta data, so we cannot simply remove it. Can we keep the `default` layout?

2024-02-02 17:51 UTC, federicobucchi commented on index.md
> -title: Welcome to Swift.org
Done.  I did it to avoid the title to show up in `index`

2024-02-02 17:51 UTC, federicobucchi commented
@swift-ci please test

2024-02-02 18:00 UTC, alexandersandberg commented
It looks like the `list` template is back now? 😄

2024-02-02 18:24 UTC, federicobucchi commented
> It looks like the `list` layout is back now? 😄

Sorry weird push

2024-02-02 18:24 UTC, federicobucchi commented
@swift-ci please test

2024-02-02 18:38 UTC, federicobucchi commented
@swift-ci please test

2024-02-03 10:48 UTC, alexandersandberg requested changes
- `page-wide` is now not applied to /getting-started/
- 404.md and 500.md needs the `page` layout and their extra titles removed
- There seem to be some formatting issues on the home page:
![CleanShot 2024-02-03 at 11 47 40](https://github.com/apple/swift-org-website/assets/35671299/3d5246e1-b452-41e4-9122-dd52376957da)
![CleanShot 2024-02-03 at 11 47 45](https://github.com/apple/swift-org-website/assets/35671299/bf02b260-221c-42d5-8d3d-1a895ff5159a)

2024-02-03 22:17 UTC, federicobucchi commented
@alexandersandberg I think I fixed the points above

2024-02-03 23:32 UTC, federicobucchi commented
@swift-ci please test

2024-02-05 09:14 UTC, alexandersandberg reviewed
The "What's new" section is still formatted incorrectly. It's a code block instead of a list.

![CleanShot 2024-02-05 at 10 11 21](https://github.com/apple/swift-org-website/assets/35671299/73a62de5-c453-4723-9fa1-96fc87d8fda0)

I think we have to find another approach to fix these issues rather than simply removing the indentation. It's too easy to break the formatting right now, and as it's the home page, we should be very careful.

Can we use the `page-wide` template but find a way to hide the title while keeping it in the meta data?

2024-02-05 18:39 UTC, federicobucchi commented
Done!  I am using `page-wide` and reduced the indentation.
What about using `hideTitle: false` in front matter?

2024-02-05 18:39 UTC, federicobucchi commented
@swift-ci please test

2024-02-05 20:36 UTC, federicobucchi commented
@alexandersandberg done!

2024-02-05 20:37 UTC, federicobucchi commented
@swift-ci please test

2024-02-05 20:37 UTC, alexandersandberg approved these changes
Looks great! 🥳

2024-02-08 14:32 UTC, kaishin approved these changes
Looks good! We might later need to change the layout of individual pages based on feedback but this PR is a good starting point.

2024-02-12 18:03 UTC, cthielen approved these changes

2024-02-12 18:25 UTC, merged