Fix obvious problems with Windows
apple/swift-org-website pull request #5
Opened 2022-03-16 00:38 UTC by stevapple

Fix some broken or outdated Windows-related documentation.

### Motivation:

* Swift on Windows currently explicitly depends on Python 3.7. Reflect
this in our guide.
* Python version 3.7.8 doesn't exist in Windows Package Manager
repository. Point to 3.7.8150.0.
* On Swift 5.4 and later releases we'll have SwiftPM on Windows. CMake
shouldn't be suggested any more.
* Windows Package Manager can only install Swift 5.5.0 by the time, which
is obviously outdated.  Use Swift.org installers instead.

### Modifications:

* Fix Python dependency on Windows to 3.7
* Fix obvious typo in `getting-started/_repl.md`
* Fix incorrect `winget` package version
* Suggest CMake only for Swift 5.3
* Use Swift.org installer for Swift on Windows

### Result:

More precise guideline for installing and using Swift on Windows.

2022-03-16 00:44 UTC, tomerd commented
cc @compnerd

2022-03-16 00:45 UTC, tomerd commented
@swift-ci test

2022-03-16 00:50 UTC, compnerd requested changes

2022-03-16 00:50 UTC, compnerd commented on download/_windows.md
> +0. Install required dependencies:
Index by 1 please.

2022-03-16 00:50 UTC, compnerd commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
These instructions are meant to explicitly use winget, please do not replace them.

2022-03-16 00:50 UTC, compnerd commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
Please keep this as is.  The suggestion terminology here is a standard thing (e.g. `apt get install` will also suggest items) - they are not required.

2022-03-16 00:50 UTC, compnerd commented on getting-started/_installing.md
> +0. Install required dependencies:
Index by 1 please.

2022-03-16 00:50 UTC, compnerd commented on getting-started/_installing.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
Same things as before apply.

2022-03-16 00:50 UTC, compnerd commented on getting-started/_repl.md
> +so that it can be used:
Bah, I was leaving it unversioned intentionally, but you're right, there is no point.  The next snippet adds the version in explicitly :-(.

2022-03-16 00:50 UTC, compnerd commented on getting-started/_repl.md
> +set SWIFTFLAGS=-sdk %SDKROOT% -I %SDKROOT%/usr/lib/swift -L %SDKROOT%/usr/lib/swift/windows
Nice catch!

2022-03-16 00:55 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
Before we can make the latest Swift release available from winget, I don’t think it’s correct to teach others to do so.

2022-03-16 00:56 UTC, stevapple commented on getting-started/_installing.md
> +0. Install required dependencies:
This convention is picked up from the Linux part — can anyone responsible to explain this?

2022-03-16 00:58 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
The `winget` support is already broken. We cannot rely on this until we get Swift correctly versioned.

To be specific, we already have experimental RPMs for the latest release, but we’re not suggesting them on Swift.org. `winget` even doesn’t have that.

2022-03-16 00:58 UTC, compnerd commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
I backed off from doing it as someone else picked up doing the version bump.  Otherwise, I normally do bump the releases once the official version is out.  I think that this is fine.

2022-03-16 00:59 UTC, stevapple commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
Package suggestions can vary by version. Can you explain why we still "suggest" this in later releases?

2022-03-16 01:00 UTC, compnerd commented on getting-started/_installing.md
> +0. Install required dependencies:
I'm not sure what you mean by responsible here.

2022-03-16 01:00 UTC, stevapple commented
@tomerd I want to know if our guides are only intended for the latest release, or they should preserve maximum compatibility with older releases?

Swift on Windows has *much more legacy problems* due to missing optimization in early releases. For every release up to Swift 5.7, some of the restrictions or additional steps will get removed.

2022-03-16 01:02 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
`winget` maintainers appear to **reject** Swift from their releases because it lacks proper versioning, and CI is always failing.

2022-03-16 01:05 UTC, compnerd commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
I've never really had issues with getting updates merged.

2022-03-16 01:05 UTC, stevapple commented on getting-started/_installing.md
> +0. Install required dependencies:
Just want to know why they’re doing that — I’ve double-checked and found we have every index to be `0` for Linux and `1` for Apple. Neither of them respects natural increments.

2022-03-16 01:06 UTC, compnerd commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
I think that it is still useful.  Most features come in CMake before SPM.  This is the case on main as well (CMake supports more functionality).

2022-03-16 01:19 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
@compnerd Because `DiaplayVersion` validation was not a thing yet when you’re doing this.

Because we’re not able to add new releases any more, @svanimpe ended up covering Swift.Toolchain 5.5 with 5.5.3. But we cannot add Swift 5.6 at this time.

2022-03-16 01:22 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
Go and fix versioning first:(

If you already have that in mind, please share with me or @svanimpe. We’re pleased to take on the investigation.

2022-03-16 01:24 UTC, stevapple commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
Okay, it makes some sense.

But I hope we can get rid of this soon when we have full support in bootstrapping SwiftPM and use it to rebuild all other stuffs, like what we’re doing on other platforms.

2022-03-16 02:42 UTC, tomerd commented
> @tomerd I want to know if our guides are only intended for the latest release, or they should preserve maximum compatibility with older releases?
>
> Swift on Windows has much more legacy problems due to missing fine-tuning in early releases. For every release up to Swift 5.7, some of the restrictions or additional steps will get removed.

imo the instructions should reflect the latest released version, or 5.6 at this point of time.

iirc we also keep track of instruction for older releases in a special section. @shahmishal ?

2022-03-16 02:47 UTC, compnerd commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
I already have TODO notes for handling that.  The problem is how to figure out the version number in the wixproj file.  If you have an idea on how to resolve that, I'd love help/ideas.

2022-03-16 02:48 UTC, compnerd commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
I don't think that I would rather keep the suggestion for Windows, at least for a while.

2022-03-16 02:50 UTC, stevapple commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
So go on removing it, right?

2022-03-16 02:52 UTC, compnerd commented on getting-started/_installing.md
> +0. Install required dependencies:
Oh, I see what you mean.  If it's for symmetry with the Linux docs, okay, that is fair.

2022-03-16 02:59 UTC, stevapple commented on getting-started/_installing.md
> +0. Install required dependencies:
Keeps with Linux doc style

2022-03-16 03:01 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
Glad to work on that. But before it happens, let’s fall back to installer.

We can always go back to winget when the support is done.

2022-03-16 03:58 UTC, shahmishal commented
> > @tomerd I want to know if our guides are only intended for the latest release, or they should preserve maximum compatibility with older releases?
> > Swift on Windows has much more legacy problems due to missing fine-tuning in early releases. For every release up to Swift 5.7, some of the restrictions or additional steps will get removed.
> 
> imo the instructions should reflect the latest released version, or 5.6 at this point of time.
> 
> iirc we also keep track of instruction for older releases in a special section. @shahmishal ?

@stevapple I would like to understand more about the difference between current (5.6) and previous release guidelines for Windows. We would like to keep the instruction for latest release.

2022-03-16 04:07 UTC, stevapple commented
@shahmishal AFAIK:
- Swift 5.3 vs 5.4: SwiftPM available; CMake no longer suggested.
- Swift 5.4 vs 5.5: installer capably of installing support files; copying support file no longer required.
- Swift 5.5 vs 5.6: I didn't notice internal changes yet. Swift 5.6 cannot be installed from `winget` as for now.
- Swift 5.6 vs 5.7: Move from VS2019 & Python3.7 to VS2022 & Python 3.9; `%SWIFTFLAGS%` no longer required.

2022-03-16 04:08 UTC, compnerd commented
> @shahmishal AFAIK:
> 
> * Swift 5.3 vs 5.4: SwiftPM available; CMake no longer suggested.


> * Swift 5.4 vs 5.5: installer capably of installing support files; copying support file no longer required.
> * Swift 5.5 vs 5.6: I didn't notice internal changes yet. Swift 5.6 cannot be installed from `winget` as for now.
> * Swift 5.6 vs 5.7: Move from VS2019 & Python3.7 to VS2022 & Python 3.9; `%SWIFTFLAGS%` no longer required.

2022-03-16 04:14 UTC, stevapple commented
> `%SWIFTFLAGS%` never was "required" - it was a way to make it easier for users to pass flags.

Right, but isn’t that Swift 5.7 with the new driver requires no additional flags at all?

> VS2022 has no meaning for the users.

UR right, I have reworded that.

2022-03-16 04:16 UTC, stevapple commented
Since winget will never be available for 5.6.0, I’m still on suggesting installer for now. We can change it back as soon as any compatible version is released.

2022-03-16 04:17 UTC, compnerd commented
> > `%SWIFTFLAGS%` never was "required" - it was a way to make it easier for users to pass flags.
> 
> Right, but isn’t that Swift 5.7 with the new driver requires no additional flags at all?
>

Correct, main does not require `-sdk %SDKROOT%`, but that is not the same thing.

> > VS2022 has no meaning for the users.
> 
> UR right, I have reworded that.

2022-03-16 04:20 UTC, compnerd commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
The updates take time anyway, 5.6 was just released.  I think we should leave winget as is.

2022-03-16 04:20 UTC, compnerd commented on download/_windows.md
> +The following additional Visual Studio components are **suggested** for Swift 5.3:
Sorry, I meant, I would rather keep the suggestion.

2022-03-16 04:43 UTC, stevapple commented on download/_windows.md
> +2. Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
I don’t think we can get this into any released toolchain. Please always guide the user to use latest release, I don’t want to pollute this rule.

2022-03-22 02:16 UTC, tomerd commented
@stevapple @compnerd what are the next steps with this PR?

2022-03-22 02:19 UTC, stevapple commented
@tomerd IMO we agreed with each other except for the installation step. From my side, since Swift 5.6.0 will **never** gain winget support, we should guide users to use Swift.org installer until any winget-compatible version has released.

2022-03-22 03:17 UTC, tomerd commented
This kind of guide should reflect the current state of thing, i.e whichever option is best (safest, most reliable) to install 5.6. Once a new version of Swift is out, or some other material changes has occurred to this end, we should change the instructions accordingly. The two of you are the domain experts, so its up to you to decide what is the right way for 5.6. @ me on this PR when it is ready and I will get it merged.

2022-03-22 15:27 UTC, stevapple commented
> I think that we should keep the `winget` instructions; I would be okay with a note to say that it lags behind the installers on the website and referring them to that.

This cannot convince me since the guide seems only intended for the latest stable release. Why don’t we just restore `winget` instructions when the latest version is available again?

2022-03-22 15:37 UTC, compnerd commented
Because winget is the recommended way - it is effectively the package management system on Windows.  We should cater to that even if it lags behind.

2022-03-22 19:52 UTC, tomerd commented
in effort to get this over the finish line, how about the following:

=> regarding "which tool we use to install the toolchain": We mention both options and recommend the installer, e.g.

```
* Using the native installer: 
  * Download the [latest package release](/download).
  * Run the package installer, which will install a Swift toolchain into `%SystemDrive%\Library\Developer\Toolchains`.
* Using `winget` (may be behind the official release): `winget install Swift.Toolchain`
```

=> regarding CMake, I dont see a strong reason to drop it as a "suggested" tool. We could consider changing the "suggested" language to "optional" to make it softer.

wdyt?

2022-03-23 01:08 UTC, stevapple commented
> => regarding "which tool we use to install the toolchain": We mention both options and recommend the installer

Seems good.  I force-pushed a new version taking such path.

> => regarding CMake, I dont see a strong reason to drop it as a "suggested" tool. We could consider changing the "suggested" language to "optional" to make it softer.

I’m not against keeping it though. Will continue to mark it as suggested.

2022-03-23 03:06 UTC, tomerd commented
lgtm. @compnerd?

2022-03-23 03:09 UTC, compnerd approved these changes

2022-03-23 03:09 UTC, compnerd commented on getting-started/_repl.md
> +so that it can be used:
Weird line break here, I assume that this will get rendered appropriately.

2022-03-23 20:31 UTC, tomerd commented
@swift-ci test

2022-03-23 22:03 UTC, tomerd approved these changes

2022-03-23 22:05 UTC, tomerd commented on download/_windows.md
> +0. Install Swift:
@stevapple what is `0.` here?

2022-03-23 22:05 UTC, tomerd commented on getting-started/_installing.md
> +0. Install Swift:
@stevapple what is `0.` here?

2022-03-23 22:06 UTC, compnerd commented on getting-started/_installing.md
> +0. Install Swift:
It auto enumerates the index for the list.

2022-03-24 00:57 UTC, tomerd commented
![Screen Shot 2022-03-23 at 5 55 07 PM](https://user-images.githubusercontent.com/147247/159820927-21a574f6-322f-47dc-9542-c09db4c7167b.png)

is this numbering expected? seems odd?

2022-03-24 00:59 UTC, compnerd commented
I suspect that there is something wrong with the indentation/wrapping that caused it to consider it to separate lists.

2022-03-24 00:59 UTC, tomerd commented
the README has instructions on how to run this locally, maybe worth double checking this looks right

2022-03-24 02:15 UTC, stevapple commented
@tomerd @compnerd Indentation problems are addressed.

2022-03-25 00:36 UTC, tkremenek commented
@swift-ci test

2022-03-25 02:51 UTC, tomerd commented
enumeration looks good now. thanks @stevapple @compnerd. next time please attach a screenshot of your changes - it can help avoid the extra iteration

2022-03-25 02:59 UTC, tomerd commented
@swift-ci test

2022-03-25 03:22 UTC, merged