Overhauled debugging memory leaks
apple/swift-org-website pull request #573
Opened 2024-03-01 18:37 UTC by RobinBateman808

### Motivation:

### Modifications:

### Result:

2024-03-07 22:27 UTC, RobinBateman808 commented
Hi @OxTim! Could you please take a look at these changes when you have a chance? Franz will be OOO until April 4. However, this content has already been vetted by him. Many thanks!

2024-03-12 02:19 UTC, 0xTim requested changes
Sorry for the delay @RobinBateman808 - overall looks great! A few things to tweak and then we can merge

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +    **For server Linux**, you can use tools like [Valgrind](https://valgrind.org/) or [Heaptrack](https://github.com/KDE/heaptrack) to profile your application as shown in the examples below. Althoug
This seems redundant

```suggestion
    **For Linux**, you can use tools like [Valgrind](https://valgrind.org/) or [Heaptrack](https://github.com/KDE/heaptrack) to profile your application as shown in the examples below. Although these tools are primarily used for C/C++ code, they can also work with Swift.
```

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +    **On server Linux**, Swift has built-in LeakSanitizer support that can be enabled using the `-sanitize=leak` compiler flag.
As above

```suggestion
    **On Linux**, Swift has built-in LeakSanitizer support that can be enabled using the `-sanitize=leak` compiler flag.
```

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +valgrind --leak-check=full ./test
It's probably good to at least mention that `./test` refers to the compiled program and if we need to pass any flags through to the compiler etc

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +```
I think these blocks can be marked as bash
```suggestion
```bash
```

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Replace `<mangled_symbol>` with the mangled symbol name shown in the stack trace.
It would be good to show an example of exactly what a mangled symbol is in case people get confused with addresses etc
```suggestion
Replace `<mangled_symbol>` with the mangled symbol name shown in the stack trace, e.g. `swift demangle $s4test12MemoryLeakerCACycfC`
```

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Unfortunately, the output doesn’t provide a human-readable representation of the function names because [LeakSanitizer doesn't symbolicate stack traces on Linux](https://bugs.swift.org/browse/SR-1260
Worth adding a "yet"?

Also, we need to update the URL to point to GH now that bugs.swift.org is no longer a thing

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +4.  This will install `binutils` and its related tools for working with binaries, object files, and libraries, which can be useful for developing and debugging Swift applications on a Linux server.
```suggestion
4.  This will install `binutils` and its related tools for working with binaries, object files, and libraries, which can be useful for developing and debugging Swift applications on Linux.
```

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Using a different example, here’s a short how-to using [Ubuntu 20.04](https://www.swift.org/download/) to analyze transient usage.
We should bump this to the latest Swift we support as 20.04 only has a year of support left, maybe just change to Ubuntu and lose the link

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +3. Then run it a second time for the `feature branch`:
We should add a mention that we need to change the branch and recompile

2024-03-12 02:19 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Since the code will be removed before final integration of the `feature branch`, the diff will also disappear.
This sentence is a bit confusing without code to refer to and makes a number of assumptions. Either we need to show the code or say something like "in this example the debug prints are only for testing and would be removed from the code before the branch is merged"

2024-03-14 17:59 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +    **For server Linux**, you can use tools like [Valgrind](https://valgrind.org/) or [Heaptrack](https://github.com/KDE/heaptrack) to profile your application as shown in the examples below. Althoug
Ack

2024-03-14 17:59 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +    **On server Linux**, Swift has built-in LeakSanitizer support that can be enabled using the `-sanitize=leak` compiler flag.
ack

2024-03-14 18:03 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +```
Ack

2024-03-14 22:08 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +valgrind --leak-check=full ./test
ack. this is from the existing documentation, can you please clarify what you're thinking and/or provide some language or an example?

2024-03-14 22:09 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +Replace `<mangled_symbol>` with the mangled symbol name shown in the stack trace.
ack

2024-03-14 22:11 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +Unfortunately, the output doesn’t provide a human-readable representation of the function names because [LeakSanitizer doesn't symbolicate stack traces on Linux](https://bugs.swift.org/browse/SR-1260
Which URL?

2024-03-14 22:11 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +4.  This will install `binutils` and its related tools for working with binaries, object files, and libraries, which can be useful for developing and debugging Swift applications on a Linux server.
ack

2024-03-14 22:11 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +Using a different example, here’s a short how-to using [Ubuntu 20.04](https://www.swift.org/download/) to analyze transient usage.
ack.

2024-03-14 22:12 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +3. Then run it a second time for the `feature branch`:
Noted. will revise.

2024-03-14 22:12 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +Since the code will be removed before final integration of the `feature branch`, the diff will also disappear.
noted. will revise.

2024-03-14 22:43 UTC, RobinBateman808 reviewed
@0xTim - Thanks for reviewing and your feedback. I think we're almost there. :-) I just have a couple questions that need clarification. Thanks again!

2024-03-19 00:10 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +valgrind --leak-check=full ./test
Something like

> once you've compiled your program, in this case a binary named `test`, run this `valgrind` command...

2024-03-19 00:10 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Unfortunately, the output doesn’t provide a human-readable representation of the function names because [LeakSanitizer doesn't symbolicate stack traces on Linux](https://bugs.swift.org/browse/SR-1260
```suggestion
Unfortunately, the output doesn’t provide a human-readable representation of the function names because [LeakSanitizer doesn't symbolicate stack traces on Linux](https://github.com/apple/swift/issues/55046). 
```

2024-03-19 00:12 UTC, 0xTim reviewed
Thanks!

2024-03-19 00:12 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> +Replace `<mangled_symbol>` with the mangled symbol name shown in the stack trace. For example, `<swift demangle $s4test12MemoryLeakerCACycfC>`
```suggestion
Replace `<mangled_symbol>` with the mangled symbol name shown in the stack trace. For example, `swift demangle $s4test12MemoryLeakerCACycfC`
```

2024-03-19 16:41 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +valgrind --leak-check=full ./test
Ack. Updated language. Thanks

2024-03-19 16:42 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> +Unfortunately, the output doesn’t provide a human-readable representation of the function names because [LeakSanitizer doesn't symbolicate stack traces on Linux](https://bugs.swift.org/browse/SR-1260
Updated language and link.

2024-03-19 16:43 UTC, RobinBateman808 commented
@0xTim - thanks for your time and reviews. I think we are there. Just the minor changes you suggested. I also removed some wordiness and tightened up spacing w/in the syntax.

2024-03-20 12:39 UTC, 0xTim approved these changes
This looks great thanks! 🙌

2024-03-20 12:40 UTC, merged