Add the 2024 SSWG update blog post
apple/swift-org-website pull request #576
Opened 2024-03-02 13:56 UTC by Joannis

2024-03-02 16:27 UTC, MahdiBM commented on _posts/2024-02-01-sswg-update-2024.md
> +]
Nit: extra ]

2024-03-02 16:27 UTC, MahdiBM commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition, **MongoKitten** was pitched and approved at the start of 2024. MongoKitten is a popular MongoDB driver for Swift.
You may call me selfish but i'd wish the starting package names were masked links, not just bold texts 👀.

Nit: `DiscirdBM` -> `DiscordBM`

2024-03-04 01:16 UTC, ktoso commented on _posts/2024-02-01-sswg-update-2024.md
> +]
```suggestion
```

2024-03-04 01:16 UTC, ktoso commented on _posts/2024-02-01-sswg-update-2024.md
> +We highly encourage you to have a look at the full [SSWG Community Survey 2024 Report](http://TODO), over on the Swift forums!
TODO: When we're ready to post I will make the forums post and then we merge the blog

2024-03-04 01:17 UTC, ktoso commented on _posts/2024-02-01-sswg-update-2024.md
> +- **Swift Distributed Actors** was accepted in January 2023. This package allows you to write peer-to-peer clusters in Swift, using distributed actors.
```suggestion
- **Swift Distributed Actors (Cluster)** was accepted in January 2023. This package allows you to write peer-to-peer clusters in Swift, using distributed actors.
```

2024-03-04 09:07 UTC, Joannis commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition, **MongoKitten** was pitched and approved at the start of 2024. MongoKitten is a popular MongoDB driver for Swift.
I'm all for that idea as well. Would that point to spi or github?

2024-03-04 19:02 UTC, MahdiBM commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition, **MongoKitten** was pitched and approved at the start of 2024. MongoKitten is a popular MongoDB driver for Swift.
I don't have a strong preference so both would be fine.
Github's UI looks more polished and more familiar to me, while SPI provides nice extra info about packages too. So both have their advantages. I'd just go with whatever is the theme right now when linking to packages in Swift.org posts.

2024-03-04 20:35 UTC, tayloraswift commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition, **MongoKitten** was pitched and approved at the start of 2024. MongoKitten is a popular MongoDB driver for Swift.
I suggest linking to GitHub repositories, as in the future we may want to consider packages that do not have a presence on SPI, or whose information on SPI may be inaccurate or out of date.

2024-03-12 13:20 UTC, finagolfin reviewed
Suggestions for some grammatical issues.

This post seems too brief. I suggest adding some more detail about the various projects, or writing a couple paragraphs on a particular topic, maybe a new project.

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +The SSWG has continued to focus on growing the ecosystem by incubating packages and providing guidance to package authors. We've seen a lot of new, in development and improved packages this year. One
in development -> in-development
of a new packages -> of a new package
`swift-memcache-gsoc` -> `swift-memcache-gsoc`,
last years Google summer of code -> last year's Google Summer of Code
higher level -> higher-level

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +We've seen a lot of progress on the adoption of Structured Concurrency. Most new libraries are adopting it, and we're working on a guide to help existing libraries adopt it as well. Two big drivers o
higher level -> higher-level
example -> example,

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition, thanks to the introduction of Package Plugins, we've seen the OpenAPI Generator make an entry. This plugin allows you to generate Swift boilerplate code from an OpenAPI specification. Th
for building -> to build

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +For the first time, we did run a developer community survey, aimed at collecting feedback and information about the shape and breadth of the Swift Server ecosystem.
did run -> ran

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +We analyzed the responses and used them to how we're doing with current efforts, and help direct the group's goals and efforts in the upcoming year (see below).
and used them to how -> and used them to figure out how

Missing some info there

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +For example, while the majority of respondents already use Swift Concurrency, there remain challanges in some areas with adoption.
challanges -> challenges

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +Among the highlights that shaped our goals for the next year were: a huge interest in standardized tooling for e.g. swift-format, as well as sourcekit-lsp and various IDEs.
were: a -> were a

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +- **Swift Service Context** and  **Swift Distributed Tracing** were accepted in October 2023. These packages enable distributed tracing for Swift. Rounding out the three pillars of observability.
Swift. Rounding -> Swift, rounding

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +- **DiscordBM** was accepted in October 2023. DiscirdBM is a Swift client for Discord's Bot API, and is used in Vapor's Penny bot.
DiscirdBM is -> DiscordBM is

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +In preparation for Swift 6, we'll be looking at the impact of the strict concurrency checking across the server ecosystem. We are planning to enable strict checking on every incubated package and mak
the strict -> strict
warning free -> warning-free

2024-03-12 13:20 UTC, finagolfin commented on _posts/2024-02-01-sswg-update-2024.md
> +In 2023, we've extensively prepared for a standardised HTTP server and middlewares. The in progress, Hummingbird rewrite is already taking advantage of the new HTTP types. The goal for 2024 is to pro
in progress, -> in-progress
general purpose -> general-purpose

2024-03-19 05:49 UTC, cthielen requested changes

2024-03-19 07:05 UTC, gwynne requested changes
Numerous grammar nits

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +Since our update post of 2023, [Sven A. Schmidt](https://github.com/finestructure) has joined the workgroup. Sven has already been involved with the documentation workgroup, and is known for his work
```suggestion
Since our update post of 2023, [Sven A. Schmidt](https://github.com/finestructure) has joined the workgroup. Sven has already been involved with the documentation workgroup, and is known for his work on the [Swift Package Index](https://swiftpackageindex.com).
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +- **Swift Distributed Actors (Cluster)** was accepted in January 2023. This package allows you to write peer-to-peer clusters in Swift, using distributed actors.
```suggestion
- **Swift Distributed Actors (Cluster)** was accepted in January 2023. This package enables writing peer-to-peer clusters in Swift using distributed actors.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +- **DiscordBM** was accepted in October 2023. DiscirdBM is a Swift client for Discord's Bot API, and is used in Vapor's Penny bot.
```suggestion
- **DiscordBM** was accepted in October 2023. DiscordBM is a Swift client for Discord's Bot API, and is the foundation of Vapor's Penny bot.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +- **Swift OpenAPI Generator** was also accepted in October 2023, providing a Swift code generator for OpenAPI specifications, allowing you to generate both servers and clients.
```suggestion
- **Swift OpenAPI Generator** was also accepted in October 2023, providing a Swift code generator for OpenAPI specifications and enabling generation of both servers and clients.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +Adoption of Structured Concurrency has been going strong but the journey isn't finished. In the coming year, we'll be focusing on adopting Structured Concurrency in even more libraries with the goal
```suggestion
Adoption of Structured Concurrency has been going strong, but the journey isn't finished. In the coming year, we'll be focusing on adopting Structured Concurrency in even more libraries, with the goal of making SwiftNIO an implementation detail of more and more libraries.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +In addition to working on libraries, we are also planning to work on more guides for developers of libraries and applications on how they can adopt Structured Concurrency and what benefits it brings.
```suggestion
In addition to working on libraries, we are also planning work on more guides for developers of libraries and applications, describing how to adopt Structured Concurrency and the benefits it brings.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +In 2023, we've extensively prepared for a standardised HTTP server and middlewares. The in progress, Hummingbird rewrite is already taking advantage of the new HTTP types. The goal for 2024 is to pro
```suggestion
In 2023, we've extensively prepared for a standardised HTTP server and middlewares. The in-progress Hummingbird rewrite is already taking advantage of the new HTTP types. The goal for 2024 is to produce a low-level, general-purpose HTTP server package.
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +Marketing Swift on the Server is a big focus area for 2024. With the introduction of the redesigned navigation of the [swift.org](swift.org) website, we'll be able to better showcase Swift on the Ser
```suggestion
Marketing Swift on the Server is a big focus area for 2024. With the introduction of the redesigned navigation of the [swift.org](https://swift.org/) website, we'll be better able to showcase Swift on the Server. 
```

2024-03-19 07:05 UTC, gwynne commented on _posts/2024-02-01-sswg-update-2024.md
> +We're looking to create more content for the ecosystem, such as integrated example projects and showcases of Swift-Server projects.
```suggestion
We're looking to create more content for the ecosystem, such as integrated example projects and showcases of existing server-focused projects.
```

2024-03-21 07:50 UTC, ktoso commented on _posts/2024-02-01-sswg-update-2024.md
> +The SSWG has continued to focus on growing the ecosystem by incubating packages and providing guidance to package authors. We've seen a lot of new, in development and improved packages this year. One
@Joannis and let's link to this year's edition https://www.swift.org/gsoc2024/

2024-03-21 09:21 UTC, Joannis commented on _posts/2024-02-01-sswg-update-2024.md
> +
The survey was done halfway through last year

2024-03-21 09:42 UTC, ktoso commented on _posts/2024-02-01-sswg-update-2024.md
> +## Adoption of Structured Concurrency
@Joannis how about we state this as sswg maintained libs being expressed in surface APIs in concurrency concepts. Compatibility with service lifecycle etc?

2024-03-26 22:22 UTC, cthielen commented
@Joannis @FranzBusch @ktoso I took an editorial pass - could you take a look and make sure the links I added are correct? Also, the link to the forums post will need to be added. Lastly, I had a little rebasing trouble, so please take a look to make sure I didn't lose any commit. Otherwise, how about 3/28/24 at 10a Pacific for publishing?

2024-03-27 08:32 UTC, Joannis commented on _posts/2024-03-28-sswg-update-2024.md
> +You can read the full [SSWG Community Survey 2024 Report](http://TODO) over on the Swift forums.
Placing a marker for @ktoso here

2024-03-27 09:46 UTC, Joannis commented
@cthielen looks good to me

2024-03-28 20:13 UTC, shahmishal commented on _posts/2024-03-28-sswg-update-2024.md
> +By participating in the [Google Summer of Code](https://www.swift.org/gsoc2024/), we were able to provide [swift-memcache-gsoc](https://github.com/swift-server/swift-memcache-gsoc), which makes it ea
```suggestion
By participating in the [Google Summer of Code](/gsoc2024/), we were able to provide [swift-memcache-gsoc](https://github.com/swift-server/swift-memcache-gsoc), which makes it easier to communicate with Memcached servers. The wire protocol and higher-level connection APIs are done, with connection pools and key sharding on the roadmap.
```

2024-03-28 20:13 UTC, shahmishal commented on _posts/2024-03-28-sswg-update-2024.md
> +Marketing Swift on the Server is a big focus area for 2024. With the introduction of the redesigned navigation of the [Swift.org](https://swift.org/) website, we'll be better able to showcase Swift o
```suggestion
Marketing Swift on the Server is a big focus area for 2024. With the introduction of the redesigned navigation of the [Swift.org](/) website, we'll be better able to showcase Swift on the Server. 
```

2024-03-28 21:14 UTC, cthielen commented
@swift-ci please test

2024-03-28 21:15 UTC, cthielen approved these changes

2024-03-28 21:17 UTC, merged