Add adwaita-swift blog post
apple/swift-org-website pull request #599
Opened 2024-03-14 20:14 UTC by david-swift

Add a blog post about writing GNOME apps with Swift.

### Motivation:

This blog post should show the possibility of writing GNOME apps with [Adwaita for Swift](https://github.com/AparokshaUI/adwaita-swift) to people experienced in Swift.
The idea of writing a blog post is from @cthielen who has reviewed first versions of the post as well as @gregorni.

### Modifications:

Add the blog post markdown file to the blog folder, an image for the post to the assets, and myself to the authors file.

### Result:

A blog post about Adwaita for Swift will be available.

2024-03-19 05:47 UTC, cthielen requested changes
99% of the way there. I just left a few nits. If you get a chance to address these, I'd love to publish on 1/22 or 1/25. How's that sound? (I can handle merging and updating the date.)

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +Swift is a popular programming language particularly well-suited for creating user interfaces thanks to the clean syntax, static typing, and special features making code easier to write.
Let's just do "Swift is well-suited for …". The full "Swift is a popular programming language" is likely known to the gracious readers of swift.org. :-)

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +title: "Writing GNOME Apps with Swift"
Solid title. Thank you!

2024-03-19 05:47 UTC, cthielen commented on _data/authors.yml
> +  github: david-swift
Your choice entirely, but would you like to add an 'about'? It doesn't have to be identifying if you don't want, e.g. "David is an avid Swift fan and has been interested in GNOME for X years" or anything you like. It's a nice touch.

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +![A screenshot of the counter example app.](/assets/images/2024-03-14-adwaita-swift/demo.png)
This screenshot stretches on my browser. It'd be better to keep it at the original size and aspect ratio.

I believe we had to add some inline CSS to fix this in another post. See https://www.swift.org/blog/swift-everywhere-windows-interop/.

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +While there are already libadwaita and GTK bindings for numerous modern programming languages, including Rust, Python, and JavaScript, all official bindings follow an _imperative_ coding style.
Might be good to add the "so what?" about imperative here, e.g. "… all official bindings follow an _imperative_ coding style, which can be verbose and harder to follow than a declarative style."

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +As you can see, Adwaita for Swift is built around _data_.
"Data" is totally fine here, especially if that's how you think about it, how the docs are written, etc.. FWIW In SwiftUI, we'd probably use the word "state", which is data with the added layer of what it's used for.

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +### Cross-Platform App Development
I think you should combine this with the "GNOME App Development" paragraph. Perhaps:

"Adwaita for Swift is useful in a number of ways:

- You can write apps, using Swift, that run on Linux, macOS, and Windows with a single codebase.
- You can share backend Swift between SwiftUI apps and GNOME apps.
- You can create entirely new GNOME apps using Swift, achieving great code readability and memory safety."

(or whichever virtues make sense to you)

2024-03-19 05:47 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +- Create an app! Use the [template repository](https://github.com/AparokshaUI/AdwaitaTemplate) as a starting point and refer to the [tutorial](https://david-swift.gitbook.io/adwaita/gettingstarted).
Optional suggestion: Instead of "You get the best …", how about: "libadwaita works best on Linux. If you're on a MacBook and interested in Linux, check out Asahi Linux" etc.

2024-03-19 19:38 UTC, david-swift commented on _data/authors.yml
> +  github: david-swift
I added an about, which is a bit different from your suggestion - do you think that is ok? 

> David is a student interested in Swift and the GNOME Project.

The thing is I've been interested in GNOME for around 10 months, not that long...

2024-03-19 19:40 UTC, david-swift commented on _posts/2024-03-14-adwaita-swift.md
> +![A screenshot of the counter example app.](/assets/images/2024-03-14-adwaita-swift/demo.png)
I simply copied the CSS of the other post you linked. Does it look better now?

2024-03-19 19:52 UTC, david-swift commented on _posts/2024-03-14-adwaita-swift.md
> +As you can see, Adwaita for Swift is built around _data_.
I think maybe data is a bit more understandable for people that do not have experience in SwiftUI? For me, state sounds more like the data at a certain point in time (e.g. when the UI is updated), but that maybe isn't what it is supposed to mean in that context.

2024-03-22 05:16 UTC, cthielen commented
@david-swift Looks great! Any objection if I merge and publish this on Monday, 3/25 around 10am Pacific?

2024-03-22 06:32 UTC, david-swift commented
No, that sound really good! Thank you so much, @cthielen!

2024-03-23 04:06 UTC, dempseyatgithub commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
I am not sure what you mean by this.

With just about any UI toolkit a view can be implemented in different ways and the results would vary.

2024-03-23 04:59 UTC, david-swift commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
I wanted to stress that the screenshot below shows one way this view could be implemented. If you think this is obvious, I could also shorten this paragraph.

2024-03-23 21:04 UTC, dempseyatgithub commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
First, I don't think I mentioned it. Thank you for this post, I enjoyed reading it and found it very informative.

In terms of my comment.

I don't understand what you mean by 'the view's content can be modified from outside that view'.

Do you mean that values and even the subviews of a view can be passed in from outside the view?

And then the next statement "This means that the single view can be implemented in different ways and the results can vary."

But I don't see the connection between between the two.

And I don't know if it's obvious, its more that I think there is something informative you are trying to get across with these two sentences, but it's not clear to me what it is.

2024-03-24 04:16 UTC, cthielen commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
Good callout. @david-swift , I read this as describing "composability", i.e. depending on where a view is in the view hierarchy, it may appear different (different widths, etc.). Is that the idea? If so, perhaps something like:

"
A view can be nested within other views or added as the child of a window.

A view's content can be modified from outside that view and could be influenced by its position in the view hierarchy. This makes it easier to compose views to produce different results.
"

?

2024-03-24 06:18 UTC, david-swift commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
@cthielen yes, that's the idea. @dempseyatgithub is the new version more understandable?

2024-03-25 16:01 UTC, dempseyatgithub commented on _posts/2024-03-14-adwaita-swift.md
> +This means that the single view can be implemented in different ways and the results can vary.
@david-swift Yes, if I'm understanding correctly, the exact presentation of a view might be different depending on its surrounding context. Similar to how views in SwiftUI might appear differently when inside a `Form` or `List` view.

That is a lot more clear - thank you!

2024-03-25 16:49 UTC, cthielen approved these changes

2024-03-25 16:50 UTC, cthielen commented
@swift-ci please test

2024-03-25 17:02 UTC, cthielen commented
@swift-ci please test

2024-03-25 17:05 UTC, merged

2024-03-25 17:11 UTC, david-swift commented
Thank you so much, @cthielen, @dempseyatgithub, and @gregorni ❤