<502> Remove jump when switching page
apple/swift-org-website pull request #610
Opened 2024-03-22 19:35 UTC by federicobucchi

### Motivation:

https://github.com/apple/swift-org-website/issues/502

> The menu items shouldn't jump after changing pages

### Modifications:

Added style in: `assets/stylesheets/_screen.scss`

### Result:

The menu items are not shifting after the page change

2024-03-22 21:10 UTC, rauhul approved these changes
looks pretty good, its a bit odd that the text visually expands from the top left corner but im not sure how easy that is to fix

https://github.com/apple/swift-org-website/assets/9739930/d91ab99d-8362-41aa-9112-926eb018df95

2024-03-22 22:02 UTC, federicobucchi commented
@rauhul I didn't even notice that.  Can you please try now?

2024-03-22 22:03 UTC, federicobucchi commented
@swift-ci please test

2024-03-22 22:04 UTC, rauhul approved these changes
nice! no jumping and expanding from the center, thanks for fixing this :D

2024-03-26 17:31 UTC, alexandersandberg commented on assets/stylesheets/_screen.scss
> +    }
Will screen readers pick this duplicate text up?

2024-03-26 17:42 UTC, federicobucchi commented on assets/stylesheets/_screen.scss
> +    }
I did test with VoiceOver and it doesn't pick the duplicate text

2024-03-26 17:46 UTC, alexandersandberg requested changes
Side-effect:

![CleanShot 2024-03-26 at 18 44 44](https://github.com/apple/swift-org-website/assets/35671299/30d00bfc-ef26-476c-9871-e70a91217a1b)

Also, I feel like the drop-down arrow was better aligned before.

|Before|After|
|---|---|
|![CleanShot 2024-03-26 at 18 45 36](https://github.com/apple/swift-org-website/assets/35671299/70d3c8f4-3dca-4624-9c67-51031947f496)|![CleanShot 2024-03-26 at 18 45 09](https://github.com/apple/swift-org-website/assets/35671299/06eab9f8-7e6e-417a-97db-63da0569a065)|

2024-03-26 20:11 UTC, federicobucchi commented
@alexandersandberg 

fixed the arrow position and submenu items alignment


Before

<img width="125" alt="Screenshot 2024-03-26 at 1 08 03 PM" src="https://github.com/apple/swift-org-website/assets/59409/cae7725e-83e1-417b-a546-4d16f03dc808">

After

<img width="120" alt="Screenshot 2024-03-26 at 1 07 56 PM" src="https://github.com/apple/swift-org-website/assets/59409/c9c79779-2a79-4e91-ad4c-d9b4bbd5f9ec">

2024-03-26 20:12 UTC, federicobucchi commented
@swift-ci please test

2024-03-26 21:01 UTC, kaishin approved these changes
Using a pseudo-element is a clever trick. I am not convinced that bolding the active link is worth the trouble compared to other ways to visually differentiate the active link, but it solves the jumpiness problem for now :+1:

2024-03-27 17:36 UTC, federicobucchi commented
@swift-ci please test

2024-04-03 18:59 UTC, alexandersandberg approved these changes
Apologies for the slow response — looks good!

2024-04-03 19:00 UTC, merged