<497> Add anchors to main sections
apple/swift-org-website pull request #613
Opened 2024-03-24 05:00 UTC by federicobucchi

### Motivation:

https://github.com/apple/swift-org-website/issues/497

### Modifications:

- `assets/stylesheets/_screen.scss` > added style to show `#` on `h2` hover
- `assets/javascripts/application.js` > adding `anchors` for each `h2` with `id` in the seen page

### Result:

Only targeting `h2` with `id` for now.

<img width="893" alt="Screenshot 2024-03-23 at 9 48 26 PM" src="https://github.com/apple/swift-org-website/assets/59409/0f2c9be9-ec5f-4af4-93a1-6deab2a8603a">

<img width="883" alt="Screenshot 2024-03-23 at 9 49 00 PM" src="https://github.com/apple/swift-org-website/assets/59409/783e8c6a-9e0e-4987-8f75-c8f20be73c21">

2024-03-24 05:37 UTC, federicobucchi commented
@swift-ci please test

2024-03-24 09:10 UTC, alexandersandberg commented
I believe this is a duplicate of #517?

2024-03-26 20:54 UTC, kaishin reviewed
I am inclined to vote for doing this using Jekyll if possible.

2024-04-23 22:47 UTC, federicobucchi commented
@kaishin @alexandersandberg updated

2024-04-24 17:41 UTC, federicobucchi commented
@daveverwer I added the `title` and the `chain link` icon.

I didn't move it to the left because I found that (in my research) that most of the anchors were placed on the left of the heading.

<img width="1111" alt="Screenshot 2024-04-24 at 10 38 27 AM" src="https://github.com/apple/swift-org-website/assets/59409/a017c80f-d1d7-4edb-988a-2b82af25a0f9">

---

<img width="1117" alt="Screenshot 2024-04-24 at 10 38 38 AM" src="https://github.com/apple/swift-org-website/assets/59409/3dfbcf1c-d872-412c-9010-66fd1d547b96">

2024-04-24 17:43 UTC, federicobucchi commented
@swift-ci please test

2024-04-24 22:41 UTC, daveverwer approved these changes
Looks great!

2024-05-07 10:33 UTC, kaishin requested changes
The site wasn't building due to an unescaped character.

2024-05-07 10:33 UTC, kaishin commented on _plugins/convert-header.rb
> +        format_as_block_html("h#{level}", el_attribute, "#{inner(el, indent)} <a title=\"Permalink for #{inner(el, indent)}\ section" href=\"##{el_attribute['id']}\">
```suggestion
        format_as_block_html("h#{level}", el_attribute, "#{inner(el, indent)} <a title=\"Permalink for #{inner(el, indent)}\ section\" href=\"##{el_attribute['id']}\">
```

2024-05-07 10:38 UTC, kaishin commented
@federicobucchi Beside the build issue above, the anchors are always visible on `h4`. They are also vertically misaligned and appear larger compared to the text.

We can perhaps use CSS to size the SVG using type-related units (`em`, `rem`) etc and if that doesn't work I wonder if we should revert to "#" as it would avoid this whole category of problems.

<img width="877" alt="screenshot-2024-05-07" src="https://github.com/apple/swift-org-website/assets/519433/f4e9071d-096c-4672-85af-da3778f20424">

2024-05-07 17:55 UTC, federicobucchi commented
@swift-ci please test

2024-05-07 17:55 UTC, federicobucchi commented
@kaishin yeah that was a problem, but for now we want only `h2` so we shouldn't have the vertical align issue

<img width="464" alt="Screenshot 2024-05-07 at 10 52 50 AM" src="https://github.com/apple/swift-org-website/assets/59409/bccc5761-43e7-42de-a46a-7774c3385671">

<img width="436" alt="Screenshot 2024-05-07 at 10 54 53 AM" src="https://github.com/apple/swift-org-website/assets/59409/a724292f-4e5d-4e31-a3c0-32e3eec2dd10">

2024-05-07 18:08 UTC, federicobucchi commented
@swift-ci please test

2024-05-08 06:55 UTC, alexandersandberg commented
Not sure if I'm missing anything but I don't see any anchors anywhere when running locally. I'm on the latest commit.

2024-05-08 16:33 UTC, federicobucchi commented
@alexandersandberg I just tested, it works for me:
- Going to the page: `/getting-started/`
- Hover for example of "Using Swift"

2024-05-09 06:19 UTC, alexandersandberg commented
> @alexandersandberg I just tested, it works for me:
> 
> * Going to the page: `/getting-started/`
> * Hover for example of "Using Swift"

Ok, so it worked if I first did `LC_ALL=en_us.UTF-8 bundle exec jekyll build` and then `... serve`. Probably due to some cache. As long as it works for people pulling the code for the first time it should be fine.

We need to add dark mode support though.

![CleanShot 2024-05-09 at 08 16 43](https://github.com/apple/swift-org-website/assets/35671299/ead530d3-bd3d-4088-affd-270c54c62179)

2024-05-09 22:38 UTC, federicobucchi commented
@alexandersandberg I have no idea of what you are experiencing unfortunately.

I am running `LC_ALL=en_us.UTF-8 bundle exec jekyll serve`

I have tried with `Auto` or forcing `Light` and `Dark` themes and all works correctly for me:

<img width="297" alt="Screenshot 2024-05-09 at 3 35 49 PM" src="https://github.com/apple/swift-org-website/assets/59409/9c7a92b7-3c5e-4800-a3f9-f5a8ecf9b78d">

<img width="283" alt="Screenshot 2024-05-09 at 3 35 42 PM" src="https://github.com/apple/swift-org-website/assets/59409/8152ac70-2e94-4201-901a-64ad30757069">

2024-05-10 06:22 UTC, alexandersandberg commented
> @alexandersandberg I have no idea of what you are experiencing unfortunately.
> 
> I am running `LC_ALL=en_us.UTF-8 bundle exec jekyll serve`
> 
> I have tried with `Auto` or forcing `Light` and `Dark` themes and all works correctly for me:
> 
> <img alt="Screenshot 2024-05-09 at 3 35 49 PM" width="297" src="https://private-user-images.githubusercontent.com/59409/329405658-9c7a92b7-3c5e-4800-a3f9-f5a8ecf9b78d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzMTMsIm5iZiI6MTcxNTMyMjAxMywicGF0aCI6Ii81OTQwOS8zMjk0MDU2NTgtOWM3YTkyYjctM2M1ZS00ODAwLWEzZjktZjVhOGVjZjliNzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2RmNzU1ZjY3YjU0Nzk4OWQ1NWFmNTRlMDJhNzQxZWMzOTRlMzYzZWJjMGUzN2UwZDg3ZDc4MDQyYWZlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72TIYcItZkO9suMD7Y8OjPKnG8ek2FQn1--4QREIg_8"> <img alt="Screenshot 2024-05-09 at 3 35 42 PM" width="283" src="https://private-user-images.githubusercontent.com/59409/329405674-8152ac70-2e94-4201-901a-64ad30757069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzMTMsIm5iZiI6MTcxNTMyMjAxMywicGF0aCI6Ii81OTQwOS8zMjk0MDU2NzQtODE1MmFjNzAtMmU5NC00MjAxLTkwMWEtNjRhZDMwNzU3MDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDQ4OGI1NjMyNGZjMmU3NjE0M2IyMjg5ZmRhNjUwNjA4MmI4M2U4ZjllYTQ3ZmE4YTM2MGEyODUxZDdiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ev5lmFd1ojoblant8c2rZca1Iko4_NVgfcv-FKY_xHA">

It works for me in Firefox, but not Safari.

2024-05-10 17:33 UTC, federicobucchi commented
> > @alexandersandberg I have no idea of what you are experiencing unfortunately.
> > I am running `LC_ALL=en_us.UTF-8 bundle exec jekyll serve`
> > I have tried with `Auto` or forcing `Light` and `Dark` themes and all works correctly for me:
> > <img alt="Screenshot 2024-05-09 at 3 35 49 PM" width="297" src="https://private-user-images.githubusercontent.com/59409/329405658-9c7a92b7-3c5e-4800-a3f9-f5a8ecf9b78d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzMTMsIm5iZiI6MTcxNTMyMjAxMywicGF0aCI6Ii81OTQwOS8zMjk0MDU2NTgtOWM3YTkyYjctM2M1ZS00ODAwLWEzZjktZjVhOGVjZjliNzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2RmNzU1ZjY3YjU0Nzk4OWQ1NWFmNTRlMDJhNzQxZWMzOTRlMzYzZWJjMGUzN2UwZDg3ZDc4MDQyYWZlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72TIYcItZkO9suMD7Y8OjPKnG8ek2FQn1--4QREIg_8"> <img alt="Screenshot 2024-05-09 at 3 35 42 PM" width="283" src="https://private-user-images.githubusercontent.com/59409/329405674-8152ac70-2e94-4201-901a-64ad30757069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzMTMsIm5iZiI6MTcxNTMyMjAxMywicGF0aCI6Ii81OTQwOS8zMjk0MDU2NzQtODE1MmFjNzAtMmU5NC00MjAxLTkwMWEtNjRhZDMwNzU3MDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDQ4OGI1NjMyNGZjMmU3NjE0M2IyMjg5ZmRhNjUwNjA4MmI4M2U4ZjllYTQ3ZmE4YTM2MGEyODUxZDdiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ev5lmFd1ojoblant8c2rZca1Iko4_NVgfcv-FKY_xHA">
> 
> It works for me in Firefox, but not Safari.

I tried with Safari, Firefox and Chrome.  All works for me.

@kaishin when you have the chance can you please try too?

If I get another approval, I will merge and we can try if @alexandersandberg experiences the same in prod (there is no risk since, at worst, @alexandersandberg wouldn't see the change)

2024-05-16 08:35 UTC, kaishin approved these changes
Thanks for addressing all the issues @federicobucchi! It is working fine on my side, in Safari and other browsers, in both light and dark modes.

2024-05-16 14:41 UTC, merged