Ported overhauled performance.md doc file changes
apple/swift-org-website pull request #616
Opened 2024-03-25 19:12 UTC by RobinBateman808

### Motivation:

I edited Debug Performance Issues and Analysis documentation to increase helpfulness.

### Modifications:

I overhauled page content by adding definitions and clarity to existing content, editing for grammar and complete sentences, reducing wordiness, providing additional instructions for less-skilled users, and formatting for scannability.

### Result:

Improve usefulness and increase user adoption.

2024-03-25 19:14 UTC, RobinBateman808 commented
@0xTim - ported changes to bump against performance.md file for comparison and mitigate link/reference issues.

2024-03-28 22:17 UTC, RobinBateman808 commented
Hi @0xTim - just a friendly to remind you to take a look when you have a chance. Thank you! :-)

2024-04-02 17:52 UTC, RobinBateman808 commented
Hi @OxTim - I'd love it if you could also provide your input on this doc. I added more instructions and explanations for those (like me/recent grads) who aren't as familiar with Swift/Swift on Server.

2024-04-09 13:06 UTC, 0xTim requested changes
Thanks for this @RobinBateman808 ! Added some comments

2024-04-09 13:06 UTC, 0xTim commented on documentation/server/guides/performance.md
> +#### Example program of an inefficient flame graph
This section should be at the top so it's clear what each tool example refers to

2024-04-09 13:06 UTC, 0xTim commented on documentation/server/guides/performance.md
> -`> LD_PRELOAD=/usr/bin/libmimalloc.so  myprogram`
I think we should keep an example of linking to jemalloc for example

2024-04-09 13:06 UTC, 0xTim commented on documentation/server/guides/performance.md
> +In Swift, memory allocation and deallocation are primarily managed by the [automatic reference counting (ARC)](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automatic
This last sentence needs to be tweaked. It's very easy to see memory issues if loading large objects into memory with pure Swift

2024-04-15 18:33 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +1. **Measure performance**: Use [Xcode’s Instruments](https://help.apple.com/instruments/mac/current/) and [Linux perf](https://www.swift.org/documentation/server/guides/linux-perf.html) provide prof
@0xTim - I don't believe this makes sense ... "Use Xcode and Linux perf provide..." Maybe "Use Xcode and Linux perf **to** provide..." wdyt?

2024-04-15 18:36 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +> Important: For server-specific performance analysis, you may need to explore other profiling tools and techniques that are better suited for server-side environments.
I'm leaning towards removing it since it can be used in combination with other tools but isn't the best or easiest solution. I'll edit accordingly.

2024-04-15 19:43 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +https://github.com/brendangregg/FlameGraph
Lgtm.

2024-04-15 20:03 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +- Alternative Profiling Tools — To profile the performance of a Swift server application running on a remote server, you may need to use alternative profiling tools specifically designed for server-s
I agree it may be better to remove Time Profiler, even though it can work, it seems cumbersome. What about tools like LLDB Debugger, Swift performance testing, or profilers like Speedscope? I'm open to suggestions that others are successfully using (including code examples). @FranzBusch - any thoughts?

2024-04-15 20:08 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +> Important: For server-specific performance analysis, you may need to explore other profiling tools and techniques that are better suited for server-side environments.
Yes, this is just referencing Time Profiler. But I'm open to removing it since it seems like other tools work better and are easier to use. @FranzBusch - wdyt?

2024-04-15 20:09 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +3. Profile memory usage: Use Xcode’s [Memory Graph Debugger](https://developer.apple.com/documentation/xcode/gathering-information-about-memory-use) to identify and fix memory-related issues.
Changed.

2024-04-15 20:19 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +- **[Xcode Instruments Time Profiler](#Xcode-Instruments-Time-Profiler)**
Good catch.

2024-04-15 20:48 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +- Alternative Profiling Tools — To profile the performance of a Swift server application running on a remote server, you may need to use alternative profiling tools specifically designed for server-s
Agreed. I looked up the recommended tools again to understand the performance characteristics of Swift server applications and optimize their performance which also included:
- LLDB debugger for Swift
- Third-parter profilers such as Speedscope (maybe ???)
- Swift Performance Testing

Should we replace Time Profiler with any of these for server-side Swift?

@FranzBusch - wdyt?

2024-04-15 20:49 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +https://github.com/brendangregg/FlameGraph
Thanks.

2024-04-15 21:33 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +> Note If you use `Set<Int>` to store the `FavouriteNumber`, the by-product should indicate if a number is a `FavouriteNumber` in constant time *(O(1)*).
Added the original language back and lightly edited it. I also moved the code example above this "Note" for better visibility.

2024-04-15 21:34 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +#### Example program of an inefficient flame graph
Moved example program back to the top of section for better visibilty.

2024-04-15 21:39 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> -`> LD_PRELOAD=/usr/bin/libmimalloc.so  myprogram`
@0xTim -  Added a lightly edited version of this back into the malloc libraries section as suggested.

2024-04-15 21:43 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +In Swift, memory allocation and deallocation are primarily managed by the [automatic reference counting (ARC)](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automatic
@0xTim - I'm not exactly sure what you mean. Feel free to expand or change the language for accuracy and clarity.

2024-06-04 21:46 UTC, 0xTim commented on documentation/server/guides/performance.md
> +1. **Measure performance**: Use [Xcode’s Instruments](https://help.apple.com/instruments/mac/current/) and [Linux perf](https://www.swift.org/documentation/server/guides/linux-perf.html) provide prof
Yeah I suggested removing the `use` to clean up the language

2024-06-04 21:46 UTC, 0xTim commented on documentation/server/guides/performance.md
> +In Swift, memory allocation and deallocation are primarily managed by the [automatic reference counting (ARC)](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automatic
I think this is now redundant after the latest changes

2024-06-04 21:46 UTC, 0xTim commented on documentation/server/guides/performance.md
> +```
Lets use Jemalloc instead as mimalloc is no longer discussed in the article

```suggestion
```bash
> LD_PRELOAD=/usr/bin/libjemalloc.so  myprogram
```
```

2024-06-05 16:08 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +1. **Measure performance**: Use [Xcode’s Instruments](https://help.apple.com/instruments/mac/current/) and [Linux perf](https://www.swift.org/documentation/server/guides/linux-perf.html) provide prof
lgtm. thanks

2024-06-05 16:10 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +```
sgtm, thanks

2024-06-05 17:12 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +> Important: For server-specific performance analysis, you may need to explore other profiling tools and techniques that are better suited for server-side environments.
Removed Time Profiling and just lightly referenced in the section if users want to explore.

2024-06-05 17:13 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +- Alternative Profiling Tools — To profile the performance of a Swift server application running on a remote server, you may need to use alternative profiling tools specifically designed for server-s
Removed Time Profiler as a suggested tool.

2024-06-05 18:28 UTC, RobinBateman808 commented
@0xTim - I think we're close on this. Ptal and lmk if you have further suggestions/changes.

2024-06-05 19:28 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +In Swift, memory allocation and deallocation are primarily managed by the [automatic reference counting (ARC)](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automatic
@0xTim - I tweaked the last sentence. Please provide the correct wording if my change still doesn't address your concern. Thanks!

2024-06-05 21:08 UTC, 0xTim requested changes
One last change then good to go!

2024-06-05 21:08 UTC, 0xTim commented on documentation/server/guides/performance.md
> +```
syntax highlighting
```suggestion
```swift
```

2024-06-05 21:20 UTC, RobinBateman808 commented on documentation/server/guides/performance.md
> +```
lgtm. thanks!

2024-06-05 21:28 UTC, 0xTim approved these changes
LGTM!

2024-06-05 21:28 UTC, 0xTim commented
@swift-ci test

2024-06-05 21:37 UTC, merged