Fix number format starting over after a block of code
apple/swift-org-website pull request #617
Opened 2024-03-25 21:48 UTC by RobinBateman808

### Motivation:

Fix the sequential number list starting over after a block of code.

### Modifications:

Manually override Markdown's handling of numbered lists. 

### Result:

Maintain the continuity of sequential numbering.

2024-03-28 22:18 UTC, RobinBateman808 commented
Hi @0xTim - another friendly to check out the minor changes that should fix the numbering format issue. I appreciate your time and help! Thanks again.

2024-03-30 14:07 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> -
I thought we needed these blank lines for the Jekyll markdown parser to pick up the code blocks? Did you try running the site to see if it still renders properly?

2024-04-01 18:47 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> -
Ack. I use macOS and get this error when trying to install valgrind: "valgrind: Linux is required for this software. Error: valgrind: An unsatisfied requirement failed this build". Should I remove the "macOS" option/instruction set since Linux is required to run valgrin? I'm new to Swift, so trying to figure this out as I go and I'm open to suggestions for accuracy and/or improvements for people like me.

2024-04-09 13:09 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> -
Ah sorry I meant running the website to see what the generated pages look like. The README for this repo has instructions on how to do that.

As an aside, what command did you try to install valgrind? `brew install valgrind` works fine for me

2024-04-09 13:10 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> -
But yes we should remove the macOS option here - valgrind won't run on macOS

2024-04-15 23:07 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> -
@0xTim - I removed the macOS option. If this all looks good to you, feel free to merge. Thanks Tim!

2024-04-18 18:30 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> -
@FranzBusch - Can you also PTAL for accuracy? Thanks!

2024-04-19 23:26 UTC, 0xTim requested changes
@RobinBateman808 there are several formatting issues with the removed newlines. If you run the site locally you'll spot them

2024-04-19 23:26 UTC, 0xTim commented on documentation/server/guides/memory-leaks-and-usage.md
> -
We need this, otherwise it breaks the formatting

![Uploading Screenshot 2024-04-20 at 00.26.04.png…]()

2024-04-22 18:05 UTC, RobinBateman808 commented on documentation/server/guides/memory-leaks-and-usage.md
> -
@0xTim - I believe I fixed the numbered formatting issues. However, I can't see the screenshot you added above. Please feel free to suggest changes to the language or code that are needed for accuracy. Thanks!

2024-04-22 21:13 UTC, RobinBateman808 reviewed
Please review these formatting changes (bullets and numbers).

2024-04-24 00:06 UTC, RobinBateman808 reviewed
@0xTim - Changed number number sequence to steps to correct formatting issues.

2024-05-04 14:43 UTC, 0xTim approved these changes
Looks like the latest changes fixed the formatting, thanks!

2024-05-04 14:43 UTC, 0xTim commented
@swift-ci test

2024-05-04 14:50 UTC, merged