Overhauled allocations documentation for helpfulness
apple/swift-org-website pull request #643
Opened 2024-04-18 19:49 UTC by RobinBateman808

### Motivation:

Edited documentation to improve helpfulness for new and experienced Swift on Server (SOS) users.

### Modifications:

Added new information, expanded on existing content, and formatted for scannability. 

### Result:

Increase users and bolster the SOS community.

2024-04-21 16:31 UTC, kaishin commented
@0xTim

2024-05-13 13:55 UTC, 0xTim requested changes
Thanks for this! See comments

2024-05-13 13:55 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +.package(url: "https://github.com/apple/swift-log.git", from: "1.4.2"),
Nit these should be indented

2024-05-13 13:55 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +let httpClient = HTTPClient(eventLoopGroupProvider: .shared(eventLoop),
What's happened to the formatting here?

2024-05-13 13:55 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +--width 1600 > out.svg
Indentation

2024-05-13 13:55 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +In the Allocation instrument, there are two categories of allocations:
Is this part specific to Xcode Instruments?

2024-05-13 13:55 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +
Given the rest of the document focuses on `perf` and Linux profiling, I'd suggest we remove all Xcode stuff below this (i.e. just leave the link above)

2024-05-13 18:31 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +let httpClient = HTTPClient(eventLoopGroupProvider: .shared(eventLoop),
Not sure how that happened, but changed it back to what it should be.

2024-05-13 18:32 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +.package(url: "https://github.com/apple/swift-log.git", from: "1.4.2"),
added indents

2024-05-13 18:35 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +--width 1600 > out.svg
added indent

2024-05-13 18:35 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +In the Allocation instrument, there are two categories of allocations:
removed OS instruments content

2024-05-13 18:36 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +
removed macOS/Xcode instruments info

2024-05-13 18:56 UTC, RobinBateman808 commented
@0xTim - made changes as suggested and corrected code formatting.

2024-05-20 18:56 UTC, 0xTim requested changes
Almost there! Few last changes

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
Missing language on the code block,  re-add

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
Missing language in the code block

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
```suggestion
```bash
```

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
Missing language again
```suggestion
```swift
```

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
```suggestion
```bash
```

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
Language

2024-05-20 18:56 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +--width 1600 > out.svg
Still missing the indentation

2024-05-21 15:20 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +```
@0xTim - Thanks for the review. I'm not sure what's happening with the code. I'm not making any changes to the blocks or text unless it was something you previously caught. Any suggestions or insight would be appreciated. :-)

2024-05-23 17:08 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +```
Adjusted space before code blocks. The text renders as it should. I also added "bash" back into block.

2024-05-23 17:16 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +--width 1600 > out.svg
Added indent again....

2024-05-23 17:23 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +--width 1600 > out.svg
Added indent again. Hoping it "sticks" this time.

2024-05-23 17:33 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +```
Adjusted space before code blocks. Preview of text renders language in code block. 
<img width="924" alt="image" src="https://github.com/apple/swift-org-website/assets/157847969/79ec58bf-dc68-4740-95a8-d35999814553">

2024-05-23 18:01 UTC, RobinBateman808 commented
@0xTim - Hopefully, the latest changes will fix things. Thanks for your time and patience! :-)

2024-05-29 20:00 UTC, RobinBateman808 commented
Hi @0xTim - Friendly bump when you have a moment. :-)

2024-06-04 19:43 UTC, 0xTim requested changes
Sorryfor the delay @RobinBateman808 

For language I mean the language of the code in the code block. So if you start a clock of code with

```
```swift
```
That tells the site generator to add the `language="swift"` tag to the generated code block so the syntax highlighter can process the code block and show syntax highlighting. This appears to have been removed in many of the code blocks so we should add them back to make it easier to read. Some options are
```
```swift
```docker
```bash
```

2024-06-04 19:43 UTC, 0xTim commented on documentation/server/guides/allocations.md
> +```
This hasn't been added?

2024-06-04 20:36 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +```
I checked the code block against the original. Looks the same.

2024-06-04 20:38 UTC, RobinBateman808 commented on documentation/server/guides/allocations.md
> +```
Apologies, I missed this. Has been corrected and checked 2x.

2024-06-04 20:45 UTC, 0xTim approved these changes
Thanks! This looks good to go

There are a few existing code blocks for running commands that could be annotated with 
```
```bash
```
But since they're existing it shouldn't hold up the PR (note that the output of the different commands _shouldn't_ have a language applied) and can be done in a separate PR if desired

2024-06-04 20:45 UTC, 0xTim commented
@swift-ci test

2024-06-04 21:05 UTC, 0xTim commented
@swift-ci test

2024-06-04 21:06 UTC, merged

2024-06-04 21:18 UTC, RobinBateman808 commented
Thanks @0xTim! I'll create a new PR to remove the applied language for the outputs.

2024-06-04 21:19 UTC, 0xTim commented
@RobinBateman808 It's all good, there wasn't any applied languages and I added all the missing ones before merging as it was a quick fix

2024-06-05 16:17 UTC, RobinBateman808 commented
Ack. Thanks!