[Articles] Add Emacs article.
apple/swift-org-website pull request #669
Opened 2024-05-22 13:59 UTC by al45tair

Add an article showing how to get started with Swift using Emacs.

rdar://127610658

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +Emacs is a highly customizable text editor that has its
Recommend spelling out Emac on the first mention and link to an educational resource to allow users to learn more about it if they want. Maybe something like, "Editor Macros, also known as [Emacs](https://en.wikipedia.org/wiki/Emacs), is a highly customizable editor...."

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +origins in a macro package for the DEC TECO editor.  A number of
Consider spelling out what DEC and TECO mean on the first mention—for example, Digital Equipment Corporation (DEC) Text Editor and Corrector (TECO). Then you can use acronyms throughout the rest of the document.

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +years, but this guide will focus on GNU Emacs.
Same for GNU ... "...but this guide will focus on [GNU's Not Unix (GNU)](https://en.wikipedia.org/wiki/GNU) Emacs."

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +There are generic [installation instructions on the GNU Emacs
Consider starting this sentence with an action-oriented word-for example, "Follow this guide to walk you through..."

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +The [Emacs for OSX](https://emacsformacosx.com) website provides
Recommend changing the wording to **Emacs for Mac OSX** to match the actual page title for clarity.

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +image from that site, opening it and dragging it to your Applications
Consider referencing as `Applications` if it's a UI term. If referring to a placeholder, you can use italics _Applications_.

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +There is [a Windows installer on the Swift
Again, recommend starting the sentence with an action-oriented word: "Use the Windows installer on the Swift website..."

2024-05-28 16:55 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +#### Ubuntu 18.04
Maybe consider linking to the currently published [dependencies for Linux](https://www.swift.org/install/linux/#installation-via-tarball) instead of duplicating?

2024-05-28 16:56 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +Emacs veterans probably remember downloading and installing Lisp
Consider defining Lisp as "...installing list processing (Lisp) packages to easily manipulate data strings, but these days..."

2024-05-30 09:42 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +origins in a macro package for the DEC TECO editor.  A number of
DEC is possibly worth expanding, even though it no longer exists as an entity, but expanding TECO is I think a bit pointless and doesn't really add any useful information.

2024-05-30 09:43 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +years, but this guide will focus on GNU Emacs.
I don't think we need to expand GNU here, honestly. The audience this article is written for will either already know what it stands for, or actually not care. Also, GNU Emacs is the name of the editor; it isn't just Emacs (since there's Lucid Emacs, XEmacs, Microemacs and probably many others), and it isn't called "GNU's Not UNIX Emacs".

2024-05-30 09:45 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +There are generic [installation instructions on the GNU Emacs
Except 99% of users are going to _not_ want to follow that guide but instead use the instructions we've got immediately below. I think we should leave this as-is.

2024-05-30 09:46 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +image from that site, opening it and dragging it to your Applications
Seems reasonable to highlight it somehow. I'll go with `Applications` for now.

2024-05-30 09:54 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +We'll also configure MELPA, which is a popular package repository for
The link is a good idea. Expanding it, not so much IMO (it doesn't really matter what it stands for, and "Milkypostman" lends an unserious air to the entire thing).

2024-05-30 19:13 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-emacs.md
> +Emacs is a highly customizable text editor that has its
Ack. Thanks.

2024-06-04 20:38 UTC, 0xTim requested changes
Overall looks good. The article needs the Jekyll metadata to be able to do a proper review though as I can't see the generated content without it (no HTML page is created)

2024-06-05 15:49 UTC, 0xTim approved these changes
Overall looks good - some queries around code blocks and we should probably have a bigger discussion around how to link to installing Swift

2024-06-05 15:49 UTC, 0xTim commented on documentation/articles/zero-to-swift-emacs.md
> +## Installing Swift
I'm in two minds about including this section - it could get out of date pretty quickly, especially with the work being done in #676. I'd probably vote for just linking to that page

2024-06-05 15:49 UTC, 0xTim commented on documentation/articles/zero-to-swift-emacs.md
> +$ sudo apt-get install emacs
Not am massive fan of including the `$` - it makes copy and pasting commands harder and isn't consistent with shell commands across the rest of the site

2024-06-06 15:18 UTC, al45tair commented
@swift-ci Please test

2024-06-06 15:19 UTC, al45tair commented
@swift-ci Please test

2024-06-06 15:21 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +## Installing Swift
I'm happy to rewrite this however anyone wants, and if linking elsewhere is sufficient, that's great.

2024-06-06 18:41 UTC, bnbarham commented on documentation/articles/zero-to-swift-emacs.md
> +## Installing Swift
+1 for just linking out to the install page

2024-06-07 11:32 UTC, al45tair commented on documentation/articles/zero-to-swift-emacs.md
> +## Installing Swift
I've updated to link out to the install page.

2024-06-07 11:33 UTC, al45tair commented
@swift-ci Please test

2024-06-07 16:45 UTC, merged