[Articles] Getting started setting up Neovim for Swift
apple/swift-org-website pull request #675
Opened 2024-05-23 22:05 UTC by etcwilde

This is an article on setting up Neovim for Swift development. It covers setting up a package manager, LSP, auto-completions, snippets, and finally some helpful autocommands.

rdar://127610592

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +SourceKit-LSP is increasingly relying on the editor informing the server when
```suggestion
SourceKit-LSP increasingly relies on the editor informing the server when
```

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +certain files change. This need is communicated through "dynamic registration".
IMO italics look nicer than quotes for definitions.

```suggestion
certain files change. This need is communicated through _dynamic registration_.
```

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +Sometimes you'll want to open swift interface files or SIL files. By default,
Either "Swift interface" or "`.swiftinterface`".

```suggestion
Sometimes you may want to open `.swiftinterface` files or SIL files. By default,
```

Also, SIL files are probably a compiler-engineer-only game?

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +Restarting vim, you will have syntax highlighting for swift interface and SIL
```suggestion
Restarting vim, you will have syntax highlighting for `.swiftinterface` and SIL
```

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +configured correctly. This should give you foundation for building your
```suggestion
configured correctly. This should give you a foundation for building your
```

2024-05-24 12:34 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +TODO: Finish this
Finish this?

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +swiftinterface files or find yourself reading SIL. If you already have Neovim,
is swiftinterface a UI term? If so, consider putting it in backticks. Spell out all acronyms the first time it's mentioned for clarity. For example:
- SourceKit Language Server Protocol (LSP) server
- SIL should be written as: Swift Integration Layer (SIL)

Then you can use just the acronym throughout the documentation.

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +
Add a lead-in sentence for this list. Maybe something like, "Here's a list of topics that we'll cover in this guide:"

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/neovim/neovim/blob/master/INSTALL.md#install-from-download
Consider embedding long GitHub links using the specific name of the section to add clarity. For example in the sentence, "Alternatively, the neovim GitHub repository has downloadable packages with the
latest versions. See [Install from download](https://github.com/neovim/neovim/blob/master/INSTALL.md#install-from-download) for more information."

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +and IDE tools needed for a Swift development experience.
Spell out Integrated Development Environment (IDE) on first mention.

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +That drops a `swift-5.10-RELEASE-ubuntu22.04/usr` directory in our Downloads
Is Downloads part of the UI? If so, consider changing to `Downloads`

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +We have working copies of neovim and Swift on our path. While we can start with
Capital **N**eovim versus lower-case **n**eovim?

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +While it's possible to set everything up by hand, using a package manager helps
Consider changing "While it's possible to set everything up by hand," to "While it's possible to set everything up manually,"

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +correctly when copy your configuration to a new computer. Neovim has a builtin
Think this is built-in with a hyphen

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +plugin management support, but I have found `lazy.nvim` to work well, so we'll
Same goes for plug-in

2024-05-24 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +start with a little bootstrapping script to install lazy if it isn't already,
is **lazy** a UI term? If so, consider writing it as `lazy`

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/folke/lazy.nvim?tab=readme-ov-file#%EF%B8%8F-configuration.
Consider embedding this link using the name of the actual content it renders: [lazy.nvim Configuration](https://github.com/folke/lazy.nvim?tab=readme-ov-file#%EF%B8%8F-configuration)

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +To check that it's working, launch neovim. You should first see an error saying
Neovim (upper case?)

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +that there were no specs found for module plugins. This just means that we don't
plug-ins instead of plugin?

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +plugins loaded. There should only be one right now, "lazy.nvim". This is Lazy
is "lazy.nvim" a UI term here? If so, can write as: `lazy.nvim`

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +I've created a little example Swift package that computes Fibonacci numbers
Maybe consider linking to an official/credible resource that explains Fibonacci numbers for users who aren't familiar with it?

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +Now that we have our plugins set, lets configure the plugin. The `nvim-cmp`
plug-ins?

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/L3MON4D3/LuaSnip
Consider adding a lead-in sentence to provide context and embed the GH link?

2024-05-24 23:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +including the popular TextMate format, VSCode format, its own Lua-based API, and
Consider writing VSCode as Visual Studio Code (VScode)

2024-05-24 23:08 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
@etcwilde - Paris requested I TAL at this and provide some very high-level documentation writing comments. Plmk if you have questions. :-)

2024-05-28 21:16 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +that there were no specs found for module plugins. This just means that we don't
It's pretty common to omit the hyphen in `plugin`. Neovim's own documentation omits the hyphen in `plugin` so I'd prefer to match that.

2024-05-28 21:19 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/L3MON4D3/LuaSnip
While I'm not married to it, I was trying to make it very clear where the plugin is coming from. Each section starts with a link to the plugin doing the heavy-lifting so that it's clear where to look for docs, or just poke around in the plugin itself.

2024-05-28 21:22 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +that there were no specs found for module plugins. This just means that we don't
Noted to align with Neovim's documentation.

2024-05-28 21:22 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +start with a little bootstrapping script to install lazy if it isn't already,
Ack. You may want to italicize it to call it out from the rest of the text.

2024-05-28 21:55 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +swiftinterface files or find yourself reading SIL. If you already have Neovim,
Ended up removing the autocmd bit. `SIL` is really something that only a compiler engineer working on Swift will care about. If folks want it back, I can bring it back, but I don't know that it's worth having just for swift interfaces.

2024-05-28 21:57 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +
That's what I was trying to do with this

> We will start by installing Neovim and Swift and then install `lazy.nvim` to
 manage our plugins. Then we'll configure the SourceKit-LSP server, setup
 Language-Server-driven autocompletion with `nvim-cmp`, and snippets with
 `LuaSnip`.

2024-05-29 22:09 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/L3MON4D3/LuaSnip
Ack. I think you can simply say that to set expectations and make it clear to users. Something like, "Each of these sections shows the link to the plugin to help you find the documentation or explore the plugin itself."

2024-05-29 22:30 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +
Noted.

2024-05-29 23:01 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +`Lazy` will list the plugins loaded.
I believe "Lazy" is the product name here. Recommend removing the backticks and just writing it as Lazy. However, if/when referring to it in UI terms, put it in backticks.

2024-05-29 23:04 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +From the `Lazy` menu, pressing `I` will install new plugins, `U` will update the
I believe Lazy here is used as a product name in this sentence. Recommend writing as Lazy and not 'Lazy'.

2024-05-30 17:11 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +plugins loaded. There should only be one right now, "lazy.nvim". This is Lazy
"lazy.nvim" is the full name of the plugin itself. I've changed all of the instances of "Lazy" to _lazy.nvim_ to match the name in the plugin documentation and readme page.

2024-06-04 20:30 UTC, 0xTim requested changes
The article needs the Jekyll metadata to be able to generate an HTML file. It's impossible to check things like `Lua` syntax highlighting work without it

2024-06-04 20:30 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +```sh
I'm not sure this is on the list of supported languages for the syntax highlighter, it should probably be
```suggestion
```bash
```

2024-06-04 20:30 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +https://github.com/L3MON4D3/LuaSnip
I agree, the link here seems like a typo

2024-06-05 16:02 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of the *vi text editor*, with a lot of new functionality piled
Tbh, this should probably read vim instead. 🤔

2024-06-05 16:16 UTC, 0xTim approved these changes
Nothing blocking - some discussion to be had around code blocks and linking to installing Swift

2024-06-05 16:16 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> + $  tar xf swift-5.10-RELEASE-ubuntu22.04.tar.gz
Not a massive fan of the leading `$` as it makes it harder to copy commands

2024-06-05 16:16 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> + $  sudo snap install nvim --classic
It might be nice to also mention other installation methods for different platforms?

2024-06-05 16:16 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +That drops a `swift-5.10-RELEASE-ubuntu22.04/usr` directory in our `~/Downloads`
We should link to the Install Swift page on Swift.org as that contains a comprehensive guide for all the different platforms, especially once #676 is landed.

2024-06-05 16:16 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +## Packaging with _lazy.nvim_
Is this deliberately italicised? Feels like monospaced would be better

2024-06-05 16:16 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +```snipmate
As an FYI there's no syntax highlighting for this file, but I can't see it as a supported library in Highlight.js

2024-06-05 16:17 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +development on Ubuntu 22.04. I have pre-installed the Solarized theme so the
I'm assuming this works on other flavours of Linux (and Windows and macOS as well? Would be good to clarify that here

2024-06-05 16:21 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +## Packaging with _lazy.nvim_
Yeah, that's the name of the plugin.

2024-06-05 16:22 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +```snipmate
That's fine I suppose. Not much I can do about that. At least it'll highlight correctly if someone looks at the markdown file in the repo. 😅

2024-06-05 16:35 UTC, etcwilde commented
I think I can rework the introduction a little bit more.

2024-06-05 16:58 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> + $  tar xf swift-5.10-RELEASE-ubuntu22.04.tar.gz
Hmm, I was using the prompt to indicate what was command vs output from the command (at least in the blocks above and below). Should I not include the output and just have the commands then? 

Some sites know how to drop the leading prompt character so copy-paste only copies the commands themselves and not the prompt character or the output from the command, is there a way to indicate to swift.org what should by copied and shouldn't be in a code block?
Another school of thought is that copy-pasting commands is a security anti-pattern since it has been used for malicious attacks in the past.

2024-06-05 21:38 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> +download page on [swift.org](https://download.swift.org) and download the release Swift
The download page has now been deprecated and no longer linked to on the homepage in favour of the new download page

2024-06-05 21:38 UTC, 0xTim commented on documentation/articles/zero-to-swift-nvim.md
> + $  tar xf swift-5.10-RELEASE-ubuntu22.04.tar.gz
Yeah we don't have a good story for that at the moment unfortunately

2024-06-06 15:13 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> + $  tar xf swift-5.10-RELEASE-ubuntu22.04.tar.gz
We can just turn off selection for the prompt: https://github.com/apple/swift-org-website/pull/694

This will work if you use

    ```console
    $ some-command -lots -of -options
    Output goes here
    ```

which will render as

```console
$ some-command -lots -of -options
Output goes here
```

but the `$ ` at the beginning will no longer be selectable.

2024-06-06 17:15 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of the *vi text editor*, with a lot of new functionality piled
@etcwilde - Spelled out "vim" on first use. Edited introduction to align tense (present), changed from first person to active voice, and reformatted for easier scannability per style guidelines.

2024-06-06 18:40 UTC, bnbarham commented on documentation/articles/zero-to-swift-nvim.md
> +That drops a `swift-5.10-RELEASE-ubuntu22.04/usr` directory in our `~/Downloads`
Yeah, IMO this entire section can essentially just become a link to "install Swift"

2024-06-06 21:52 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
I have mixed feelings on expanding vim. It's technically not wrong, but I don't think it helps with comprehension and makes it a little awkward to read. Thoughts? @al45tair, what do you think? Maybe I've been looking at this for too long?

2024-06-06 23:00 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
Ack. The recommendation is based on standard writing style guidelines. Exceptions can be made if your target audience already understands the terminology and definition.

2024-06-07 16:36 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
I'd probably make sure that I spelled it Vim, rather than in all lowercase, unless it's a command in which case `vim`. I don't think I'd expand it — I think it's a name at this point. It's also a little tricky to expand, because `vi` was a shortening of **VI**sual, so `vim` is a play on words — it's both **VI**sual and **IM**proved.

In any event, I think the audience is likely familiar with Vim.

2024-06-07 17:10 UTC, al45tair commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
(Having read through it, a few times, I don't _mind_ the expansion either, so if you want to leave it how it is, that's fine by me.)

2024-06-07 17:19 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
_Neo-VIsual-IMproved (Neovim)_ intensifies. No, I think that looks silly and I think that will actually confuse more people than it helps.

I'll go ahead and capitalize the name though.

2024-06-07 19:38 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> + $  sudo snap install nvim --classic
I moved the link to the Neovim install page up above this block so that folks are aware of it. See what you think.

2024-06-07 20:21 UTC, shahmishal approved these changes

2024-06-07 20:54 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +Neovim is a modern reimplementation of _Vi IMproved (vim)_, a popular terminal-based text
I'm good with the majority vote. Thanks!

2024-06-07 20:57 UTC, RobinBateman808 approved these changes

2024-06-07 21:03 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +of Neovim. I'm running Ubuntu 22.04 on an `x86_64` machine. Unfortunately, the
Recommend starting a new paragraph with: "I'm running Ubuntu 22.24..."

2024-06-07 21:05 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +support many of the APIs that we will be using. For this install, I used `snap`
Also Recommend starting a new paragraph with: "For this install, I used `snap`..."

2024-06-07 21:07 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +start with a little bootstrapping script to install _lazy.nvim_ if it isn't
Recommend starting a new paragraph with: "We will start with a little bootstrapping...."

2024-06-07 21:20 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +To check that it's working, launch Neovim. You should first see an error saying
The last nit ... consider formatting for easier readability:

"To check that it's working:
1. Launch Neovim. 
You should first see an error saying that there were no specs found for module plugins. This just means there aren't any plugins. 
2. Press Enter and type, `:Lazy`. 
_lazy.nvim_ will list the plugins loaded. There should only be one right now: "lazy.nvim". This is _lazy.nvim_ tracking and updating itself. 
3. From the _lazy.nvim_ menu, press `I` to install new plugins. 
`U` updates the plugins and `X` deletes any plugins that _lazy.nvim_ installed, but are no longer being tracked in your configuration."

2024-06-07 21:36 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> +To check that it's working, launch Neovim. You should first see an error saying
There, I broke up apart the last point a bit further so that each button is a separate element.
Something I'm noticing, if I try to number them, the website generator seems very intent on renumbering all of the points as `1.` so I left them as an unordered list. Will that work?


To check that it's working:
 - Launch Neovim.

   You should first see an error saying that there were no specs found for
   module plugins. This just means that there aren't any plugins.

 - Press Enter and type, `:Lazy`.

   _lazy.nvim_ lists the plugins installed. There should only be one right now:
   "lazy.nvim". This is _lazy.nvim_ tracking and updating itself.

 - We can manage out plugins through the _lazy.nvim_ menu.
    - Pressing `I` will install new plugins.
    - Pressing `U` will update installed plugins.
    - Pressing `X` will delete any plugins that _lazy.nvim_ installed, but are
      no longer tracked in your configuration.

2024-06-07 21:39 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> +To check that it's working, launch Neovim. You should first see an error saying
That works. Thanks.

2024-06-07 21:43 UTC, RobinBateman808 commented on documentation/articles/zero-to-swift-nvim.md
> + - We can manage out plugins through the _lazy.nvim_ menu.
Oops! I think "out" should be "our"?

2024-06-07 21:44 UTC, etcwilde commented on documentation/articles/zero-to-swift-nvim.md
> + - We can manage out plugins through the _lazy.nvim_ menu.
Yep!

2024-06-07 21:46 UTC, etcwilde commented
@swift-ci please test

2024-06-07 22:06 UTC, parispittman commented
lgtm - thanks!!

2024-06-07 22:06 UTC, merged