[Article] Getting started with vscode swift
apple/swift-org-website pull request #696
Opened 2024-06-06 18:30 UTC by matthewbastien

### Motivation:

This PR adds instructions for working with the Swift extension Visual Studio Code. It provides users with information on how to install the Swift extension and use it to write, debug, and test Swift code.

### Modifications:

I've added a new page under `documentation/articles/getting-started-with-vscode-swift.md` as well as image assets under `assets/images/getting-started-with-vscode-swift`.

### Result:

A new article will exist which explains how to install and use the Swift extension for VS Code.

2024-06-06 22:54 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +The Swift extension for Visual Studio Code only supports Swift Package Manager
Recommend moving this near the end of the intro, such as after the "Installing the Swift extension..." paragraph and before the sentence:

"The extension is developed by members of the Swift community..."

2024-06-06 22:54 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +Visual Studio Code is a powerful editing tool that provides a modern and
Consider leading the intro/overview with this and providing the acronym on the first mention. For example:

"Visual Studio Code (VS Code)"

2024-06-06 22:54 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +The extension is developed by members of the Swift Community and maintained by
This seems to distract from the purpose of the article. Consider moving this to the bottom of the page.

2024-06-06 22:55 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +[Getting Started Guide on Swift.org](https://www.swift.org/getting-started/) for
Recommend removing any/all uses of the word, "Please". You can simply say:

"See the Getting Started Guide...."

2024-06-06 22:55 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +![Select a project template](/assets/images/getting-started-with-vscode-swift/create-new-project/select-project-template.png)
Consider formatting the instructions as numbered steps for sequence and easier readability. For example:

"Follow these instructions to create a new Swift project:
1. Choose from a list of project types to select a project template.
2. Choose the directory where the project will be stored....
3. Open a newly-created project.
You will be prompted to open the project in the current window, a new window, or add it to the current...."

2024-06-06 22:56 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +VS Code provides a rich debugging experience that you can read about in
Spell this out at the beginning of a sentence:

"Visual Studio Code provides a..."

2024-06-06 22:56 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +By default, the extension will create a launch configuration for each executable
Remove future-tense words such as "will". You can simply say:

"By default, the extension creates a launch config..."

2024-06-06 22:56 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +The screenshot below depicts an example of debugging a hello world program. It
Capitalize, "Hello World" to separate/call it out from the rest of the text.

2024-06-06 22:56 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +VS Code provides a Test Explorer view in the left sidebar which can be used to
Spell out VS Code at the beginning of the sentence.

2024-06-06 22:57 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +The Swift extension will automatically detect your installed Swift toolchain.
Present tense, "The Swift extension automatically detects your ...."

2024-06-06 22:57 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +to save it in User Settings or Workspace Settings. Keep in mind that Workspace
Consider formatting this sentence as a bullet list for easier reading:
"Your options are to:
- Save it in User Settings
- Save it in Workspace Settings

Keep in mind that Workspace Settings...."

2024-06-07 15:15 UTC, plemarquand commented on assets/images/getting-started-with-vscode-swift/testing/filtering_tests_by_custom_tags.png
@matthewbastien can you delete this screenshot? It feels unnecessary

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +to power language features.
```suggestion
to provide language features.
```

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +      "problemMatcher": ["$swiftc"],
```suggestion
```

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +      "problemMatcher": ["$swiftc"],
we're discouraging the problem matcher in favour of the extension controlling this

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +
maybe add compile errors and warnings will be parsed from the Swift build output. By default sourcekit-LSP errors will get precedence and remove compiler error but can that they can modify swift.diagnosticsCollection setting

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +debugger to work properly.
idk if worth noting you must have lldb in your selected toolchain otherwise you manually must set the lldb.library setting

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +tests. As you write tests they are automatically added to the Test Explorer.
maybe make clear populated by sourcekit-LSP in case they disabled it in settings? This is only the case for swift 6 or later right?

2024-06-07 15:17 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +
add code coverage and can debug a test case?

2024-06-07 15:20 UTC, plemarquand commented on documentation/articles/getting-started-with-vscode-swift.md
> +      "problemMatcher": ["$swiftc"],
@award999 So the problemMatcher array should be empty?

2024-06-07 15:21 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +      "problemMatcher": ["$swiftc"],
Personally I'd just remove it but ya at very least empty

2024-06-07 15:32 UTC, plemarquand commented on documentation/articles/getting-started-with-vscode-swift.md
> +
Done

2024-06-07 15:35 UTC, plemarquand commented on documentation/articles/getting-started-with-vscode-swift.md
> +tests. As you write tests they are automatically added to the Test Explorer.
If the LSP isn't enabled we fall back to semantic test discovery, which only works for XCTests (but works for any toolchain version). SourceKit-LSP is required for swift-testing tests. Maybe that's worth noting.

2024-06-07 15:56 UTC, matthewbastien commented on documentation/articles/getting-started-with-vscode-swift.md
> +debugger to work properly.
I was under the impression that the swift toolchains provided on swift.org will always contain LLDB. Swift debugging is impossible with any other LLDB release.

2024-06-07 15:59 UTC, matthewbastien commented on documentation/articles/getting-started-with-vscode-swift.md
> +
added a note for this

2024-06-07 16:05 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +debugger to work properly.
hmmm I may be thinking lldb-dap, will leave as is then

2024-06-07 16:07 UTC, award999 commented on documentation/articles/getting-started-with-vscode-swift.md
> +tests. As you write tests they are automatically added to the Test Explorer.
probably wordy explanation, as long as works for the older supported versions then LGTM

2024-06-07 17:37 UTC, timsneath requested changes
Some changes here... will do another pass if I can find time.

2024-06-07 17:37 UTC, timsneath commented on documentation/articles/getting-started-with-vscode-swift.md
> +cross-platform support, and benefits from active community support.
I don't think we need to sell VSCode for Microsoft. Can we just say:
> Visual Studio Code is a popular general-purpose editor that supports a variety of languages. 

...and then go onto the next sentence ("Installing the Swift extension adds...")

2024-06-07 17:37 UTC, timsneath commented on documentation/articles/getting-started-with-vscode-swift.md
> +You **must** run a build before Swift language features will be available.
- What does "run" a build mean? Do you mean that the project must be compiled? Executed? Must it be from VSCode or is it OK if you're compiling via a command line? 
- Does this apply to every project? Or is this a one-off step to get the right binary in the right places for all projects?
- And why must you "run a build" anyway? Can we add a little extra explanation?

2024-06-07 17:37 UTC, timsneath commented on documentation/articles/getting-started-with-vscode-swift.md
> +The Swift extension provides some basic tasks that you can use to build via
"built-in", rather than "basic"?

2024-06-07 17:37 UTC, timsneath commented on documentation/articles/getting-started-with-vscode-swift.md
> +The screenshot below depicts an example of debugging a Hello World program. It
"shows", rather than "depicts"?

2024-06-07 17:37 UTC, timsneath commented on documentation/articles/getting-started-with-vscode-swift.md
> +Swift-testing tests annotated with
BTW, the name for this is "Swift Testing", not "Swift-testing". Both words capitalized.

2024-06-07 18:56 UTC, plemarquand commented on documentation/articles/getting-started-with-vscode-swift.md
> +You **must** run a build before Swift language features will be available.
I've reworked this warning block, let me know if it makes more sense.

2024-06-07 19:37 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +and install [Visual Studio Code](https://code.visualstudio.com/Download).
Consider a lead-in sentence and format as steps. For example:
"Here are instructions for installing the Swift extension.

1. Install Swift.
    You must install Swift for the extension to function. See the [Getting Started](https://www.swift.org/getting-started/) for details on how to install Swift on your system.
2. Download and install [Visual Studio Code](https://code.visualstudio.com/Download).
3. Install the Swift extension from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang).
    You can also install the Swift extension from within the VS Code extensions view as shown below:“

2024-06-07 19:37 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +You can use the `Swift: Create New Project...` command provided by the Swift
Consider revising/formatting this paragraph for scannability and clarity:

To create a new Swift project, you can use the Swift: Create New Project... command in the Swift extension to guide you through the process. You can find this command by opening the Command Palette and following the instructions below.

* For macOS: CMD + Shift + P
* Other platforms: Ctrl + Shift + P

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +editor. Follow the links to see the VS Code documentation on the subject:
Maybe change, "Follow the links..." to:

"Use these links to see the VS Code documentation for each topic:"

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +VS Code provides tasks as a way to run external tools. You can read more about
Spell out the acronym since it starts the sentence:

"Visual Studio Code provides..."

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +[the VS Code Documentation](https://code.visualstudio.com/docs/editor/tasks).
Consider matching the page/article title with the link to avoid confusion:

"See the [Integrate with External Tools via Tasks](https://code.visualstudio.com/docs/editor/tasks) documentation to learn more."

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +[the VS Code Documentation](https://code.visualstudio.com/docs/editor/debugging).
Consider matching the article/page title with link name:

"Visual Studio Code provides a rich debugging experience. See the [Debugging](https://code.visualstudio.com/docs/editor/debugging) documentation for more information."

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +You can launch a debugging session via the Debug view in VS Code. Select the
Recommend formatting?

"You can launch a debugging session using the Debug view in VS Code. 

1. Select the launch configuration you wish to debug.
2. Click on the green play button to launch a debugging session. 

The executable will launch and you can set breakpoints in your Swift code that will be hit as the code executes.“

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +Visual Studio Code provides a Test Explorer view in the left sidebar which can
Consider formatting as a list for easier readability:

"Visual Studio Code provides a Test Explorer view in the left sidebar which can be used:

* To navigate.
* To run tests.
* Debug tests.

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +To debug a test, set a breakpoint and then run the test, suite, or entire test
Consider reformatting for easier readability:

"To debug a test:

1. Set a breakpoint.
2. Run the test, suite, or entire test target using the Debug Test profile.

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +line numbers that were executed during a test appear green, and those that were
add a comma between: "As you browse covered files, line numbers..."

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +Swift Testing tests annotated with
Maybe break the run-on sentence into two sentences?

"Swift-testing tests annotated with [tags](https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/addingtags) can be filtered in the Test Explorer using @TestTarget:tagName. You can then run or debug the filtered list of tests."

2024-06-07 19:38 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +pick up the new toolchain. You must do so otherwise the extension will not
Add a comma after "You must do so, otherwise..."

2024-06-07 20:36 UTC, timsneath approved these changes

2024-06-07 21:27 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +![Package swift actions](/assets/images/getting-started-with-vscode-swift/language-features/package_actions.png)
Slight nit, I'd move this below the paragraph that starts with, "SourceKit LSP also provides code actions to automate..." and change the wording in the parenthesis to: (see the screenshot below)

"

2024-06-07 21:30 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +1. Select the launch configuration you wish to debug
add a period at the end of this sentence: 

"Select the launch configuration you wish to debug."

2024-06-07 21:31 UTC, RobinBateman808 commented on documentation/articles/getting-started-with-vscode-swift.md
> +2. Click on the green play button to lauch a debugging session.
correct spelling for "launch" (missing an `n`)

2024-06-07 21:36 UTC, RobinBateman808 approved these changes
Approved with last three suggested changes.

2024-06-07 22:09 UTC, parispittman approved these changes

2024-06-07 23:53 UTC, federicobucchi commented
@swift-ci please test

2024-06-08 00:41 UTC, federicobucchi approved these changes

2024-06-08 00:41 UTC, merged