Align "workgroup" spelling
apple/swift-org-website pull request #90
Opened 2022-06-18 19:36 UTC by alexandersandberg

This fixes #89.

### Motivation:

As discussed among SWWG, we decided that it would be a good idea to align the spelling of "workgroup" according to the [Apple Style Guide](https://help.apple.com/applestyleguide/). This is the first step in a plan to introduce a style guide for Swift.org content.

### Modifications:

- Change any occurrences of "work group(s)" to "workgroup(s)"...
  - in static website content
  - in two recent blog posts
  - in `_data/authors.yml` for Diversity in Swift workgroup

### Discussions:

**Should we also update the spelling of "workgroup" in older blog posts?**

**Should we also update the spelling of "workgroup" in personal author bios in `_data/authors.yml`?**

2022-06-18 19:36 UTC, alexandersandberg commented
@swift-ci test

2022-06-19 15:58 UTC, tomerd approved these changes

2022-06-20 09:50 UTC, 0xTim approved these changes

2022-06-20 19:40 UTC, tomerd commented
cc @tkremenek

2022-06-20 20:44 UTC, shahmishal requested changes

2022-06-20 20:44 UTC, shahmishal commented on diversity/index.md
> +You can reach the Diversity in Swift workgroup on the Swift Forums as [@diversity-work-group](https://forums.swift.org/g/diversity-work-group).
```suggestion
You can reach the Diversity in Swift workgroup on the Swift Forums as [@diversity-work-group](https://forums.swift.org/g/diversity-workgroup).
```

Last week I updated forums.swift.org to workgroup from work-group.

2022-06-20 20:44 UTC, shahmishal commented on _data/authors.yml
>  diversity-work-group:
```suggestion
diversity-workgroup:
```
We should also update the blog post which contains this reference

2022-06-21 03:30 UTC, shahmishal commented on _data/authors.yml
>  diversity-work-group:
- _posts/2020-12-16-accessibility-and-inclusion.md
- _posts/2020-12-16-diversity-in-swift.md
- _posts/2021-05-10-swift-mentorship-program.md

2022-06-21 03:33 UTC, shahmishal commented on diversity/index.md
> +You can reach the Diversity in Swift workgroup on the Swift Forums as [@diversity-work-group](https://forums.swift.org/g/diversity-work-group).
Also, we should update line 31.

2022-06-21 03:37 UTC, shahmishal commented
Few more files we should update the text: 
- gsoc2022/index.md
   - Line 397
- mentorship-tos/index.md
   - Line 32
- mentorship/index.md 
   - Line 38, 98 and 104 


@alexandersandberg Thank you for getting the website updated to "workgroup"!

2022-06-21 06:20 UTC, alexandersandberg commented on diversity/index.md
> +You can reach the Diversity in Swift workgroup on the Swift Forums as [@diversity-work-group](https://forums.swift.org/g/diversity-work-group).
Oh, I was not aware of this change. Thanks!

https://forums.swift.org/g/diversity-workgroup seems to be private?

2022-06-21 06:36 UTC, alexandersandberg commented
Thank you, @shahmishal!

I have updated the diversity workgroup and interop workgroup references in e83f00a and 7db3888.

I also added a link to one of the diversity workgroup references in c382fcd.

2022-06-21 20:06 UTC, shahmishal commented
> Should we also update the spelling of "workgroup" in older blog posts?

It would be good to figure out how many blog posts we are talking about.

> Should we also update the spelling of "workgroup" in personal author bios in _data/authors.yml?

We should and `cc` the authors make them aware of the change.

2022-06-21 20:47 UTC, alexandersandberg commented
@shahmishal 

> It would be good to figure out how many blog posts we are talking about.

Only 3 blog posts would need to be updated:
- `_posts/2016-10-25-server-api-workgroup.md` (not sure if we need to update this as this workgroup no longer exists?)
- `_posts/2019-10-31-sswg-update-2019.md`
- `_posts/2021-03-24-womens-history-month.md`

However, as we may not enforce the planned style guide for blog posts, I would only update references to workgroups (e.g. "Swift Server Work Group"), not the use of the noun "work group" (e.g. on [this line](https://github.com/apple/swift-org-website/blob/327234d321faa7db01f3d6e7e1edcc80369298a1/_posts/2019-10-31-sswg-update-2019.md?plain=1#L142)). Does this make sense?

> We should and `cc` the authors make them aware of the change.

Good idea. 👍 I will do this.

2022-06-21 21:03 UTC, alexandersandberg commented
Hey @twostraws, @tanner0101, @tomerd, @0xTim, and @devanshimodha, I just wanted to let you know that we have made some minor updates to your author bios in this PR to align the spelling of "workgroup" across the website (more info in this PR).

See the changes [here](https://github.com/apple/swift-org-website/pull/90/files#diff-fdca1c48b249c38bee14489176341e078b9cfcf168e19ba1c669b92fa7322c49).

No action is required on your part, but please let me know if you have any concerns. Thank you! 🙂

2022-06-21 21:05 UTC, twostraws commented
No concerns – thank you! 🙌

2022-06-22 08:59 UTC, kaishin approved these changes
Much nicer! Thank you.

2022-06-24 03:51 UTC, tomerd commented
@swift-ci test

2022-06-24 06:13 UTC, shahmishal approved these changes
LGTM! Thank you!

2022-06-24 08:03 UTC, merged