Add VS Code swift extension post
apple/swift-org-website pull request #95
Opened 2022-06-30 19:18 UTC by adam-fowler

### Motivation:

Contribute a blog post about the SSWG developed Visual Studio Code Swift extension

### Modifications:

Add VSCode extension blog post markdown

### Result:

2022-06-30 19:21 UTC, adam-fowler commented on _posts/2022-06-30-vscode-extension.md
> +The Test Explorer provides a UI similar to the Xcode Tests UI. The UI contains a tree view, including all the test targets, with each XCTestCase class embedded within those targets and each individua
Not sure about the use of the word embedded in the TestExplorer section, but can't think of a better alternative. Was thinking of rewriting this section it doesn't really make total sense. There is no discrimination between the actual tests and the tree view elements that represent them.

The Test Explorer provides a UI similar to the Xcode Tests UI. The UI contains a tree view with top level elements representing each test target in your package. These top level elements then contain child elements that represent each XCTestCase class in the test targets and each XCTestCase element contain leaf elements that represent each individual test. Tests can be run outside of a debugger or in the debugger. You can run individual tests, or filter the tests being run by class, name or test target, or just run all tests. The UI updates as tests succeed or fail.
What do you think?

2022-06-30 19:46 UTC, 0xTim approved these changes
I'm guessing we're leaving out package editing until it stabilises in 5.7?

I also think we should call out Steven for the initial work on the extension. 

Otherwise LGTM other than a few nits

2022-06-30 19:46 UTC, 0xTim commented on _posts/2022-06-30-vscode-extension.md
> +Visual Studio Code uses a number of JSON configuration files to set up your development environment. The Swift extension will auto-generate these files for your SwiftPM project so you won't need to m
```suggestion
Visual Studio Code uses a number of JSON configuration files to set up your development environment. The Swift extension will auto-generate these files for your SwiftPM project so you won't need to manually set them up. When you load a project, the extension creates build tasks for everything in your project, along with debug and release versions for any executables in your `Package.swift`. It will also create debugger launch configurations for debug and release builds of all executables.
```

2022-06-30 19:46 UTC, 0xTim commented on _posts/2022-06-30-vscode-extension.md
> +The Test Explorer provides a UI similar to the Xcode Tests UI. The UI contains a tree view, including all the test targets, with each XCTestCase class embedded within those targets and each individua
Yeah makes sense, or replace embedded with contained

2022-06-30 19:46 UTC, 0xTim commented on _posts/2022-06-30-vscode-extension.md
> +The Remote - Containers extension allows you to run Visual Studio Code inside a Docker container to compile and test your code inside that container. It is possible to use this with the Swift extensi
Is it worth providing a link to the extension or the docs?

```suggestion
The **Remote - Containers** extension allows you to run Visual Studio Code inside a Docker container to compile and test your code inside that container. It is possible to use this with the Swift extension to test/debug your Swift code. This is particularly useful if you are developing on macOS but deploying to Linux as differences in Linux and macOS performance or features can be caught early.
```

2022-06-30 19:48 UTC, 0xTim commented
@swift-ci test

2022-06-30 21:08 UTC, shahmishal commented on _posts/2022-06-30-vscode-extension.md
> +# Swift Extension for Visual Studio Code
We should add post header

Example:
```
---
layout: post
published: true
date: 2022-06-15 09:20:00
title: Announcing the Language Workgroup
author: tkremenek
about: Ted Kremenek is a member of the Swift Core Team and serves as the voice of the Project Lead.  Ted manages the Languages and Runtimes group at Apple.
---
```

2022-06-30 21:16 UTC, tkremenek commented
Do we want a screenshot or anything in the post?

2022-07-01 15:11 UTC, alexandersandberg commented on _posts/2022-06-30-vscode-extension.md
> +# Swift Extension for Visual Studio Code
FYI, `about` the author does not have to be included in the post header. This information is fetched from `authors.yml`.

I see @adam-fowler is not in the author list though. Might be a good idea to add yourself. 🙂

2022-07-01 16:00 UTC, tkremenek commented
We don't need to be shy with screenshots, even small ones.  Many Swift.org posts are a bit dry with being mostly text.  Given that this is talking about specific tool work where we have the opportunity to _show_ the extension in action, there is an opportunity to show all the key pieces that are working.

2022-07-01 16:54 UTC, adam-fowler commented on _posts/2022-06-30-vscode-extension.md
> +# Swift Extension for Visual Studio Code
Is the author link the swift forum username?

2022-07-01 17:08 UTC, adam-fowler commented
@tkremenek where should I put the images?

2022-07-01 17:10 UTC, shahmishal commented
> @tkremenek where should I put the images?
You can place them here:
https://github.com/apple/swift-org-website/tree/main/assets/images

2022-07-01 22:18 UTC, alexandersandberg commented on _posts/2022-06-30-vscode-extension.md
> +# Swift Extension for Visual Studio Code
@adam-fowler The identifier is only used internally and can be anything, but preferably one of your usernames. You can also add `twitter` and `github` properties which will link to your profiles.

2022-07-02 16:12 UTC, adam-fowler commented
> We don't need to be shy with screenshots, even small ones. Many Swift.org posts are a bit dry with being mostly text. Given that this is talking about specific tool work where we have the opportunity to _show_ the extension in action, there is an opportunity to show all the key pieces that are working.

How about a movie? I've just added a symbol completion movie.

2022-07-03 02:37 UTC, tkremenek commented
> > We don't need to be shy with screenshots, even small ones. Many Swift.org posts are a bit dry with being mostly text. Given that this is talking about specific tool work where we have the opportunity to _show_ the extension in action, there is an opportunity to show all the key pieces that are working.
> 
> How about a movie? I've just added a symbol completion movie.

The video looks great!

2022-07-03 02:41 UTC, tkremenek commented
<img width="587" alt="vscode-lsp-screenshot" src="https://user-images.githubusercontent.com/3087023/177022370-8ef03179-0d11-4f4e-831a-cca5dbc27657.png">

2022-07-03 02:42 UTC, tkremenek commented
@swift-ci test

2022-07-03 12:29 UTC, alexandersandberg commented on _posts/2022-06-30-vscode-extension.md
> +author: adam-fowler
Note: You also need to add an entry in [`authors.yml`](https://github.com/apple/swift-org-website/blob/main/_data/authors.yml) with the same identifier (`adam-fowler`). You can see some examples of how to format that entry in that file. 🙂

2022-07-04 07:32 UTC, alexandersandberg approved these changes

2022-07-07 05:38 UTC, cthielen commented on _posts/2022-06-30-vscode-extension.md
> +The extension is primarily targeted at Swift Packager Manager (SwiftPM) projects. It consists of a number of components already available as well as new ones, all brought together into one coherent p
"Below is a list of some of the key features" feels unnecessary.

2022-07-07 05:56 UTC, cthielen commented on _posts/2022-06-30-vscode-extension.md
> +The [Swift Server Work Group](https://www.swift.org/sswg/) (SSWG) felt there was a need for a more complete solution. The Swift Extension for Visual Studio Code from the SSWG brings together many of
"Work Group" or "Workgroup"?

2022-07-07 07:30 UTC, alexandersandberg commented on _posts/2022-06-30-vscode-extension.md
> +The [Swift Server Work Group](https://www.swift.org/sswg/) (SSWG) felt there was a need for a more complete solution. The Swift Extension for Visual Studio Code from the SSWG brings together many of
Thanks for catching that! As of https://github.com/apple/swift-org-website/pull/90, it should be "Workgroup".

2022-07-07 07:32 UTC, alexandersandberg requested changes

2022-07-07 07:32 UTC, alexandersandberg commented on _posts/2022-06-30-vscode-extension.md
> +The [Swift Server Work Group](https://www.swift.org/sswg/) (SSWG) felt there was a need for a more complete solution. The Swift Extension for Visual Studio Code from the SSWG brings together many of
```suggestion
The [Swift Server Workgroup](https://www.swift.org/sswg/) (SSWG) felt there was a need for a more complete solution. The Swift Extension for Visual Studio Code from the SSWG brings together many of these components into one package with everything pre-configured to work from the get-go.
```

Thanks, @cthielen!

2022-07-07 16:13 UTC, adam-fowler commented on _posts/2022-06-30-vscode-extension.md
> +The extension is primarily targeted at Swift Packager Manager (SwiftPM) projects. It consists of a number of components already available as well as new ones, all brought together into one coherent p
removed

2022-07-07 22:52 UTC, alexandersandberg approved these changes

2022-07-08 23:07 UTC, 0xTim commented
@tkremenek are we good to merge?

2022-07-11 16:35 UTC, tomerd commented
@0xTim we should let @cthielen merge - we should discuss more on the next workgroup meeting

2022-07-14 16:37 UTC, merged